### ISSUE TITLE
don't start on gentoo

### ISSUE THREAD

**Issue by brothermechanic** [slytomcat/yandex-disk-indicator#1]
Hello
Thank you for developing!
But i can't to try in, because it don't start
[code]
$ yandex-disk-indicator

(yandexDiskIndicator.py:25311): GLib-GIO-ERROR **: Settings schema 'apps.yandex-disk-indicator' is not installed

/usr/bin/yandex-disk-indicator: line 3: 25311 Trace/breakpoint trap   ./yandexDiskIndicator.py

I tryed install from git and from deb package
Wat's the problem?

**Comment by slytomcat** [comment]
You have to install gsettings schema 'apps.yandex-disk-indicator'

In debian/ubuntu it can be done via following commands:

sudo cp <path>/apps.yandex-disk-indicator.gschema.xml /usr/share/glib-2.0/schemas/
sudo glib-compile-schemas /usr/share/glib-2.0/schemas

Deb package installation should perform necessary actions automatically.

But I'm not shure which tools to use in gentoo for this task :(

**Comment by slytomcat** [comment]
In version 1.4.2 I've changed place where indicator stores its settings. Now it is file in ~/.config/yd-tools/ that is created when file doesn't exists on indicator start.

This sould fix the issue you have. Just get the latest version of indicator
