### ISSUE TITLE
Не запускается в elementary OS 

### ISSUE THREAD

**Issue by jonywtf** [slytomcat/yandex-disk-indicator#153]
Установил через apt, иконка появилась (яндекс диск на тот момент уже был сконфигурирован через консоль и синхронизировался). При клике на иконку ничего не происходит.
Загрузил архив отсюда, выполнил yandex-disk-indicator.py
Получил такое:

```
** (yandex-disk-indicator.py:17754): WARNING **: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-emKvUVCxVb: В соединении отказано
2016-05-18 14:53:25,337 ERROR    Config file read error: /home/user/.config/yd-tools/yandex-disk-indicator.conf
Traceback (most recent call last):
  File "./yandex-disk-indicator.py", line 1494, in <module>
    activateActions()
  File "./yandex-disk-indicator.py", line 1349, in activateActions
    res = subprocess.call(["gksudo", "-D", "yd-tools", "cp", ctr_pub, ctr_unpub, ctrs_path])
  File "/usr/lib/python3.4/subprocess.py", line 537, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.4/subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.4/subprocess.py", line 1457, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] Нет такого файла или каталога: 'gksudo'
```

Очевидно что нету gksudo, установил: `sudo apt-get install gksu`
заработало, но было бы очень классно если бы оно сразу заработало)
Возможно как-нибудь это предусмотреть? добавить в зависимости?

**Comment by slytomcat** [comment]
К сожалению это проблема с файловыми расширениями для Pantheon-files. Это единственный ФМ у которого установка расширений не может быть сделана через настройки в пользовательском домашнем каталоге, более нигде нет потребности в gksudo - все остальные функции индикатора должны и работают под текущим пользователем.

Поэтому включать в зависимости gksu не считаю разумным.

**Comment by slytomcat** [comment]
Что бы не вываливалось с ошибкой поменял в https://github.com/slytomcat/yandex-disk-indicator/commit/fb788077051a2428ba09b529e07736494b791bce обработку исключений в функции активации файловых расширений - просто будет ошибка в логгировании, а функция просто закончится неудачей.
