### ISSUE TITLE
Перестал запускаться в Ubuntu 15.10

### ISSUE THREAD

**Issue by ingeniero071** [slytomcat/yandex-disk-indicator#154]
На днях yandex-disk-indicator (1.8.15) "на ровном месте" перестал запускаться. 
Из консоли и при помощи ярлыка результат одинаковый.
В логах так:

2016-05-28 13:56:20,073 INFO     yandex-disk-indicator v.1.8.15
2016-05-28 13:56:20,073 DEBUG    Logging level: 10
2016-05-28 13:56:20,074 DEBUG    Config value read as: theme = False
2016-05-28 13:56:20,075 DEBUG    Config value read as: notifications = True
2016-05-28 13:56:20,075 DEBUG    Config value read as: autostart = True
2016-05-28 13:56:20,075 DEBUG    Config value read as: daemons = ~/.config/yandex-disk/config.cfg
2016-05-28 13:56:20,075 DEBUG    Config value read as: fmextensions = True
2016-05-28 13:56:20,075 INFO     Config read: /home/warrior/.config/yd-tools/yandex-disk-indicator.conf
2016-05-28 13:56:20,075 DEBUG    Lock file is:/home/warrior/.config/yd-tools/pid
2016-05-28 13:56:20,076 DEBUG    Lock file succesfully locked.
2016-05-28 13:56:20,099 DEBUG    Config value read as: auth = /home/warrior/.config/yandex-disk/passwd
2016-05-28 13:56:20,099 DEBUG    Config value read as: dir = /home/warrior/Yandex.Disk
2016-05-28 13:56:20,099 DEBUG    Config value read as: proxy = False
2016-05-28 13:56:20,100 INFO     Config read: /home/warrior/.config/yandex-disk/config.cfg
2016-05-28 13:56:20,115 INFO     Change event: {stat, size, last, init}
2016-05-28 13:56:20,119 DEBUG    Sub-menu 'Last synchronized' has been updated
2016-05-28 13:56:22,124 DEBUG    Raw event Timer idle -> idle
2016-05-28 13:56:24,123 DEBUG    Raw event Timer idle -> idle
2016-05-28 13:56:27,150 DEBUG    Raw event Timer idle -> idle
2016-05-28 13:56:31,174 DEBUG    Raw event Timer idle -> idle
2016-05-28 13:56:36,199 DEBUG    Raw event Timer idle -> idle
2016-05-28 13:56:42,223 DEBUG    Raw event Timer idle -> idle
2016-05-28 13:56:49,247 DEBUG    Raw event Timer idle -> idle

Ставил из репо.
Переустановка с ключом purge не помогает, в логах - то же самое.
Что можно сделать?

**Comment by slytomcat** [comment]
А какой он этот одинаковый результат? 
По логу если судить - то все работает. Иконки нет?

**Comment by ingeniero071** [comment]
Имею ввиду, что если в CLI вызвать yandex-disk-indicator и если вызвать при помощи ярлыка, то иконка не появляется в обоих случаях. Да, мне тоже показалось, что лог как-будто нормальный, только "Raw event Timer idle -> idle" немного смущает, не известно, что это означает. 

По пути /home/warrior/.config/yd-tools/icons  в директориях /light и /dark пусто, иконок нет.
В директории /usr/share/yd-tools/icons/light есть иконки.

**Comment by slytomcat** [comment]
"Raw event Timer idle -> idle"  - это обычное отладочное сообщение - не более и не менее - смущать не должно.
Если в хомяке иконок нет то берутся из /usr/...

Как вариант иконки нет т.к. нет аплета индикаторов в панели. Хотя на это должна бы быть ругань... Еще вариант - в настройках аплета иконка явно скрыта.

**Comment by ingeniero071** [comment]
Странно, всегда иконка была явной и находилась в трее. 
Как узнать, явно скрыта или нет?
Содержимое .config/yd-tools/yandex-disk-indicator.conf:

theme="no"
notifications="yes"
autostart="yes"
daemons="~/.config/yandex-disk/config.cfg"
fmextensions="yes"

Рассуждаю логически.
Прога работала нормально. В один из дней, выдало "ошибка синхронизации", затем я ее закрыл из трея. Это был последний раз, когда видел иконку :)
Перегрузил lightdm.
Переустановил дважды прогу. Удаляя всякий раз с Purge, то есть по полной.
И после переустановки иконка не появялется. Это странно.
Если после переустановки проги иконка не появляется, при этом иконки проги пристутввуют в нужной дир., то получается что-то не так с системой? Удалилась какая-то из нужных библиотек?

**Comment by ingeniero071** [comment]
Update. Посмотрел history CLI. В период, когда проявилась проблема, удалял этих товарищей:
apt-get -y purge zeitgeist zeitgeist-core zeitgeist-datahub
apt-get -y purge gnome-orca unity-webapps-common telepathy-*

Установил заново, заметил, что вместе с ними ставятся очень много зависимостей, особенно связанных с питоном\* .
В итоге, индикатор в трее не появился, но при перезапуске самого диска, один раз появилась иконка "Синхронизация запущена". Правда, больше не появлялась :)
Может проблема в этой плоскости?

**Comment by slytomcat** [comment]
Да, скорее всего что-то из необходимых питоновских библиотек снесли вместе zeitgeist и ко.
Плохо то что по зависимостям индикатора нужное не подтянулось. 

Я попробую разобраться где там произошла накладка и добавить нужное в зависимости индикатора.

**Comment by Zeirison** [comment]
Добрый день, похожую проблему наблюдаю в Cinnamon. Если нажать **"Удалить этот апплет"**, то его невозможно будет восстановить, не помогает удаление конфигов и переустановка. С чем может быть связана проблема и можно ли её решить?

**Comment by slytomcat** [comment]
Долго копался в зависимостях - так и не понял что там могло потеряться да еще так, что бы индикатор перестал работать и не ругался при этом...

Однако пробовал побаловаться с апплетом индикаторов (XFCE) и нашел там такой глючек - убираешь известные индикаторы и индикаторы все пропадают (хотя приложение продолжает работать). Но лечится просто перезапуском индикатора - он появляется снова.

Почему-то мне кажется что корень этой проблемы в работе апплета индикаторов. И самое неприятное, что они разные под разные DE и могут глючить поразному... 

Куда копать - толком не понятно....

**Comment by ingeniero071** [comment]
А что такое апплет индикаторов? Поищу, посмотрю что там как устроено...
Ну у меня не XFCE, а LightDM, может у него своя специфика...

**Comment by slytomcat** [comment]
LightDM - это только "запускалка" у меня он тоже есть, но запускает XFCE, в котором и есть десктоп, на нем панель, а впанели плагины и один из плагинов панели - плагин индикаторов - именно он используется для вывода иконки индикатора.

**Comment by ingeniero071** [comment]
Удалил полностью индикатор (purge), затем autoremove, затем ручным поиском по ОСи удалил файлы конфигурации и прочие относящиеся к программе файлы, затем заново установил из реп-ия. Заработал.

**Comment by ingeniero071** [comment]
Проблем вернулась. Во время синхронизации появилось сообщение "Ошибка синхронизации", после перезапуска индикатора в трее он больше не появился. В логе, как и ранее, пусто, все в штатном режиме. При этом диск синхронизируется нормально, никакой ошибки нет. В первый раз проблема началась точно таким же образом.

**Comment by slytomcat** [comment]
Так какой дистрибутив? Я пробовал на виртуалке в разных *ubuntu - воспроизвести не смог.
Т.е. удалить то индикатор из плагина индикаторов можно, но он там появляется после следующего запуска индикатора (старый при этом нужно руками прибить). И в KDE (kubuntu), и в LXDE(lubuntu) и Unity(ubuntu) - ситуация одинаковая (хотя плагины разные).

**Comment by ingeniero071** [comment]
Дистрибутив все тот же, что указан в названии Issue: Ubuntu 15.10 с Unity.

**Comment by slytomcat** [comment]
Ок погоняю еще в виртулке, пока не могу воспроизвести...

**Comment by ingeniero071** [comment]
Ок, я думаю, Вам нужно смоделировать ситуацию, когда индикатор выдает сообщение в трее "ошибка синхронизации" и посмотреть его дальнейшее поведение. 

Какие события генерируют такое сообщение? Возможно на этом этапе и происходит сбой: сам сервис Яндекс диск синхронизирует файлы в штатном режиме. По какой-то причине индикатор в процессе этой синхронизации выдает "ошибка..." и после перезапуска отказывается появляться в трее)

**Comment by slytomcat** [comment]
Ок, попробую.

**Comment by slytomcat** [comment]
Так и не смог воспроизвести.

Поясните пожалуйста - вот это: "Во время синхронизации появилось сообщение "Ошибка синхронизации", после перезапуска индикатора в трее он больше не появился."

Как именно вы перезапускали? 
И что именно была за ошибка? - ее можно посмотреть если кликнуть по статусу в меню индикатора.

**Comment by ingeniero071** [comment]
Уже не помню, наверное имел ввиду, что перезапускал сам диск.
"Ошибка синхронизации" - это всплывающее сообщение индикатора. В правом углу возле иконки появляется, небольшое такое. Такое же, как и другие, пренадлежащие индикатору. Не помню уже их содержание. Смысл в том, что это обычное всплывающее сообщение.

Посмотреть нельзя, индикатор-то не виден в трее, значити всплывающих сообщений нет.

У меня появилась новая теория, почему так происходит. MS Word, сохраняет резервные копии файлов в процессе работы. Типа автосохранинение. Если файл находится на ЯД (клиент под Виндоус), то Word сохраняет копии на ЯД. Например, оригинал файла имеет название Текстовый файл (1).doc,  Имена копий в таком случае имеют вид: Текстовый файл (1).doc, Tекстовый файл (2).doc. Когда ЯД клиент под Убунту (с которым работает индикатор) синхронизирует такие файлы, они синхронизируются нормально. Но индикатор после этой синхронизации выдает всплывающее собщение  "ОШИБКА СИНХРОНИЗАЦИИ" (по-моему текст всплывающего сообщения заглавными буквами там) и пропадает из трея.
После понлного удаления индикатора, и переустановки он появлялся в трее, но стоило синхронизировать такие копии - он пропадал. Дважды такое повторялось. Совпадение?

**Comment by ingeniero071** [comment]
Проблема, очевидно, кроется в трее Unity.
Нашел способ заставить трей показывать значки при помощи стороннего индикатора: http://forum.ubuntu.ru/index.php?topic=258603.0

Соответственно в трее значки появились, в том числе значок индикатора яндекс.диска.
