### ISSUE TITLE
Некорректно сохраняет настройки прокси в конфиге

### ISSUE THREAD

**Issue by burrbull** [slytomcat/yandex-disk-indicator#155]
Добавляет кавычки вокруг каждого параметра прокси:
proxy="тип", "адрес", "порт"

Должно быть
proxy="тип,адрес,порт"

**Comment by slytomcat** [comment]
fixed in https://github.com/slytomcat/yandex-disk-indicator/commit/d77b2386c48d5634d72148fa8d3c458a287e378e

**Comment by slytomcat** [comment]
Проблема была в том, что все прочитанные данные из конфигурации демона перезаписывались. Но, дело в том, что конфиг с форматом записи key="val,val,val" - это специальная обработка (т.к. штатно в конфиги пишутся в формате key="val","val","val" или key=val,val,val) и заточена она была только на изменяемый параметр exclude-dirs.
Можно было спец-форматирование применить и к proxy, но т.к. эта переменная в самом индикаторе никак не изменяется, то я просто убрал перезапись этой переменной.
