### ISSUE TITLE
1.8.18 post-installation script was killed

### ISSUE THREAD

**Issue by ktullanux** [slytomcat/yandex-disk-indicator#157]
Привет.
При обновлении системы получил

```
Setting up yd-tools (1.8.18) ...
dpkg: error processing package yd-tools (--configure):
 subprocess installed post-installation script was killed by signal (Terminated)
Errors were encountered while processing:
 yd-tools
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

Видимо что-то с /var/lib/dpkg/info/yd-tools.postinst
Вылечил его, но так делать плохо

```
#!/bin/bash
exit 0
done
```

**Comment by slytomcat** [comment]
Вот блин. 

Переделал там немного скритпы инсталляционные - что-то напортачил....

Собственно сам пакет хоть и с ошибкой, но встает - индикатор обновляется. Падает скрипт который я пилил - он должен перезапускать индикатор при обновлении пакета.... но что-то там не так.... пока копаю.

**Comment by ktullanux** [comment]
Может, в пост инсталл просто добавить
`pkill yd-tools`
или не вариант? :))

**Comment by slytomcat** [comment]
pkill yd-tools вернет код ошибки 1 если ни одного индикатора не запущено в данный момент - будет ошибка инсталяции.

Я в prerm удаляю их в цикле 
for pid in $(pgrep yd-tools)
do 
  kill $pid
done
Такой код никогда не выдает ошибок в процессе выполнения и скрипт отрабатывает нормально.

Проблема в том что я хотел сделать не просто удаление процессов а перезапуск. И вот с эти выходит какая-то чертовщина... пока не понял в чем дело... но если не разберусь, то пока просто уберу этот функционал.

**Comment by slytomcat** [comment]
Разобрался в чем косяк.

Оказывается когда pgrep yd-tools запускается в постинсталяционном скрипте, то он находит самого себя (постинсталяционный скрипт) и самого себя же киляет. Пока не понял как побороть - пробую разные варианты... гуглю...

**Comment by ktullanux** [comment]
А можно сделать так, чтобы призапуске yd-tools он писал свой PID в файл, а при исполнении постинсталяционного скрипта киллял его? Или тоже велосипед? :D

**Comment by slytomcat** [comment]
PID файл есть (/run/user/<uid>/yandex-disk-indicator.pid), но он - не самое надежное решение, ИМХО.

Да и чисто теоретически индикатор может одновременно работать под несколькими пользователями (с разными uid).

**Comment by MInner** [comment]
@ktullanux спасибо, не знал где лежит этот скрипт

**Comment by slytomcat** [comment]
Победил. Обновление на гите (master, dev). Вечером залью в PPA (с работы нет доступа туда, смогу только дома)

**Comment by slytomcat** [comment]
Fixed in 1.8.19
