### ISSUE TITLE
Openfl Yandex.Disk Folder bug

### ISSUE THREAD

**Issue by R3D9477** [slytomcat/yandex-disk-indicator#166]
Hi. When I try to open folder of yandex disk via menu then will be opened several copies of filemanager with yandex.disk.

Linux Mint 18 x64

Window List:
![screenshot at 2016-11-01 09-20-13](https://cloud.githubusercontent.com/assets/15020827/19881159/8b51798a-a014-11e6-8a6a-ea74ccb8b75c.png)

Thanks

**Comment by slytomcat** [comment]
Hi. How many instances opened from one try?
Can You repeat the problem with debugging output from indicator that started from command line by following command:
    `yandex-disk.indicator -l10`

**Comment by slytomcat** [comment]
I've found the problem.
Fix is applied in v. 1.9.6

**Comment by R3D9477** [comment]
many thanks!
