### ISSUE TITLE
Запуск проверки с начала.

### ISSUE THREAD

**Issue by Baasis** [slytomcat/yandex-disk-indicator#168]
Здравствуйте.
Заметил странное поведение.
По несчастью пришлось зайти на win, а там тоже стоит яндекс диск.
В папках ничего не менялось. Единственное винда могла только загрузить себе что-то, но в win я ничего не удалял и не добавлял.
Так вот после возврата в lin запустился процесс проверки и уже два часа 180 гигов проверяется.
Заметил уже во второй раз это.
Если яндекс диск стоит на win и на win, то проверяются только новые файлы, а вот lin с начала все проверяет.
Подскажите как быть.

**Comment by slytomcat** [comment]
Непосредственно за синхронизацию отвечает yandex-disk - утилита от Yandex. Индикатор только показывает текущий статус синхронизации и никакого влияния на этот процесс не оказывает.
Нужно сообщить о выявленной проблеме в Yandex: https://yandex.ru/support/disk/troubleshooting/sup-desktop/other.html
Только не забудьте указать версию клиента (можно посмотреть по yandex-disk -v)
