### ISSUE TITLE
Пишет статус: Не запущен

### ISSUE THREAD

**Issue by antohami** [slytomcat/yandex-disk-indicator#169]
Дистрибутив ALT Linux. Версия клиента yandex-disk-indicator 1.9.6. Версия yandex-disk 0.1.5.948.
```
yandex-disk-indicator -l10
2017-02-16 15:42:47,238 INFO     yandex-disk-indicator v.1.9.6
2017-02-16 15:42:47,239 DEBUG    Logging level: 10
2017-02-16 15:42:47,243 DEBUG    Config value read as: theme = False
2017-02-16 15:42:47,243 DEBUG    Config value read as: fmextensions = True
2017-02-16 15:42:47,244 DEBUG    Config value read as: autostart = True
2017-02-16 15:42:47,244 DEBUG    Config value read as: daemons = ~/.config/yandex-disk/config.cfg
2017-02-16 15:42:47,244 DEBUG    Config value read as: notifications = True
2017-02-16 15:42:47,244 INFO     Config read: /home/anton/.config/yd-tools/yandex-disk-indicator.conf
2017-02-16 15:42:47,427 DEBUG    Config value read as: proxy = False
2017-02-16 15:42:47,428 DEBUG    Config value read as: dir = /home/anton/Yandex.Disk
2017-02-16 15:42:47,428 DEBUG    Config value read as: auth = /home/anton/.config/yandex-disk/passwd
2017-02-16 15:42:47,428 DEBUG    Config value read as: stoponexitfromindicator = True
2017-02-16 15:42:47,429 DEBUG    Config value read as: startonstartofindicator = True
2017-02-16 15:42:47,429 INFO     Config read: /home/anton/.config/yandex-disk/config.cfg
2017-02-16 15:42:49,219 INFO     Start success, message: Запуск демона...Готово

2017-02-16 15:42:49,266 INFO     Change event: {init}
2017-02-16 15:42:49,276 DEBUG    Sub-menu 'Last synchronized' has been updated
2017-02-16 15:42:49,277 INFO     Status: none -> paused
2017-02-16 15:42:49,598 DEBUG    Event raised byTimer 
2017-02-16 15:42:49,599 INFO     Change event: {stat}
2017-02-16 15:42:49,600 INFO     Status: paused -> none
2017-02-16 15:42:49,600 DEBUG    Message: Яндекс.Диск  | Сервис Яндекс.Диск остановлен
```
Получается не может получить статус? Статус считываться должен из ~/Yandex.Disk/.sync/status ?
```
cat ~/Yandex.Disk/.sync/status
24203
```
При этом:
```
yandex-disk status
Статус ядра синхронизации: ожидание команды
Путь к папке Яндекс.Диска: '/home/anton/Yandex.Disk'
	Всего: 10 GB
	Занято: 2.71 GB
	Свободно: 7.29 GB
	Максимальный размер файла: 10 GB
	Размер корзины: 0 B

Последние синхронизированные пути:
	файл: 'Запись экрана 2016-12-18 19:41:38.mp4'
	файл: 'Включаем управление яркостью.mp4'
	файл: 'Screencast_23.03.2015_08:41:30.webm'
	файл: 'Screencast_23.03.2015_08:34:16.webm'
	файл: 'Загрузки/Builder-icex/regular-builder-icex-20151002-x86_64.iso'
	файл: 'Загрузки/Builder-icex/regular-builder-icex-qtcreator-20151005-x86_64.iso'
	файл: 'Загрузки/EPIC_FLAG.rar'
	файл: 'trikStudio/trikStudio-p7-64.tar.gz'
	файл: 'Загрузки/FLProg_1_10_Linux64.tar.gz'
	файл: 'Загрузки/Nokia N900 RX-51 Gr.RUS_sw-20.2010.36.2.exe'
```

**Comment by slytomcat** [comment]
Нет. Статус получается не из ~/Yandex.Disk/.sync/status, а из вызова yandex-disk status запущенного в пустом окружении (для того что бы вывод был в английской локали). Вывод утилиты парсится и оттуда берется статус.

Возможно у вас что-то не так с локалями. Что у вас выдает 
  `env -i LANG='en_US.UTF8' yandex-disk status`
?

**Comment by antohami** [comment]
```
env -i LANG='en_US.UTF8' yandex-disk status
Error: daemon not started
```
А закостылить можно что-то вроде такого:
```
LANG2=$LANG
LANG=en_US.UTF8
yandex-disk status | парсим команду
LANG=$LANG2
```
 ?

**Comment by slytomcat** [comment]
Это костилилось по-разному уже не раз из за разных корявых настроек LC_ переменных у пользователей. 
Установка LANG не срабатывает если установлена LC_MESSAGES.
Поэтому я запускаю демона в дефолтном, пустом окружении (env) и в нем ставлю значение LANG. Это 100% работает т.к. в дефолтном окружении переменные LC_* не установлены.
Но у вас похоже демон запущен под рутом или каки-то другим пользователем. Ведь env создает пустое окружение но пользователя не меняет, а демон у вас от вашего пользователя не запущен.

Покажите что говорит:
`ps au | grep yandex-disk`

**Comment by antohami** [comment]
```
ps au | grep yandex-disk
anton    26846  0.1  1.0 783884 83048 pts/0    Sl+  17:20   0:07 python3 /usr/bin/yandex-disk-indicator
anton    29232  0.0  0.0   8260   788 pts/4    S+   18:48   0:00 grep yandex-disk
```
Демон yandex-disk запускается демоном yandex-disk-indicator

**Comment by antohami** [comment]
Так может не переключать локаль вовсе, а локализовать текст который парсим?

**Comment by slytomcat** [comment]
Без смены локали парсить - это парсить английский, русский, белорусский, украинский и турецкий (на этих языках может выдавать свои сообщения демон). Это не здоровая идея.

Индикатор пробует запустить демона и судя по логу успешно запускает - что потом происходит - не ясно пока, но по прошествии какого-то времени после старта демон исчезает. Вот с этим и надо разбираться...
Запускайте демона руками и смотрите, что происходит (по логам) - видимо демон на чем-то падает.

**Comment by antohami** [comment]
Всё работает нормально. Я могу опубликовать файлы, синхронизация идёт. Только статус не получаем в индикаторе
env -i LANG='en_US.UTF8' похоже в Альте не работает почему-то, возможно баг. Вот к примеру:
```
env -i LANG='en_US.UTF8' echo $LANG
ru_RU.utf8
```
Что у вас эта же команда выдаст?

**Comment by slytomcat** [comment]
У меня тоже ru_RU.utf8 выдает - но это какой-то глюк. Если вызвать env без команды, то он выдает окружение, так вот он выдает так:

```
env -i LANG='en_US.UTF8'
LANG=en_US.UTF8
```

**Comment by antohami** [comment]
Короче решение проблемы на форуме Альта подсказали. Нужно, интерпретатор bash указать:
Вот так работает
LANG='en_US.UTF8' bash -c 'echo $LANG'
en_US.UTF8
И соответственно нужно:
```
LANG='en_US.UTF8' bash -c 'yandex-disk status'
Synchronization core status: idle
Path to Yandex.Disk directory: '/home/anton/Yandex.Disk'
	Total: 10 GB
	Used: 2.71 GB
	Available: 7.29 GB
	Max file size: 10 GB
	Trash size: 0 B

Last synchronized items:
	file: 'Запись экрана 2016-12-18 19:41:38.mp4'
	file: 'Включаем управление яркостью.mp4'
	file: 'Screencast_23.03.2015_08:41:30.webm'
	file: 'Screencast_23.03.2015_08:34:16.webm'
	file: 'Загрузки/Builder-icex/regular-builder-icex-20151002-x86_64.iso'
	file: 'Загрузки/Builder-icex/regular-builder-icex-qtcreator-20151005-x86_64.iso'
	file: 'Загрузки/EPIC_FLAG.rar'
	file: 'trikStudio/trikStudio-p7-64.tar.gz'
	file: 'Загрузки/FLProg_1_10_Linux64.tar.gz'
	file: 'Загрузки/Nokia N900 RX-51 Gr.RUS_sw-20.2010.36.2.exe'
```

**Comment by slytomcat** [comment]
Ну баш добавлять - это масло масленное. env по сути и есть еще одна версия баш со своим окружением.

**Comment by antohami** [comment]
Покажите, где у вас это место в коде находится

**Comment by slytomcat** [comment]
Просто echo - это команда самого баша и поэтому она печатете $LANG из первичного окружения а не из нового. yandex-disk - это отдельный процесс и он то запускается и берет LANG уже и нового окружения.

Получаю выхлоп демона я в методе YDDaemon:getOutput(self, userLang=False)
При вызове без параметров должен возвращатся выхлоп от демона в английской локали.

**Comment by slytomcat** [comment]
У вас что `env -i LANG='en_US.UTF8' bash -c 'yandex-disk status'` выдает статус, а 
`env -i LANG='en_US.UTF8' yandex-disk status` выдает что демон не запущен?

**Comment by antohami** [comment]
Тупанул.
```
env -i LANG='en_US.UTF8' bash -c 'yandex-disk status'
Error: daemon not started
```
Похоже в пустом окружении yandex-disk сам себя не видит

**Comment by slytomcat** [comment]
А что выдает 
`env -i LANG='en_US.UTF8' whoami`
?

**Comment by slytomcat** [comment]
Похоже действительно какое-то взаимное несварение у env и yandex-disk в ALT-е....

**Comment by antohami** [comment]
```
env -i LANG='en_US.UTF8' whoami
anton
```

**Comment by slytomcat** [comment]
что выдают 
ps au | grep yandex-disk
env -i bash -c "ps au | grep yandex-disk"

**Comment by antohami** [comment]
```
[anton@comp-e2-1800 BUILD]$ ps au | grep yandex-disk
anton    26846  0.1  1.0 783884 83108 pts/0    Sl+  17:20   0:13 python3 /usr/bin/yandex-disk-indicator
anton    31264  0.0  0.0   8260   868 pts/4    S+   20:02   0:00 grep yandex-disk
[anton@comp-e2-1800 BUILD]$ env -i bash -c "ps au | grep yandex-disk"
anton    26846  0.1  1.0 783884 83108 pts/0    Sl+  17:20   0:13 python3 /usr/bin/yandex-disk-indicator
anton    31269  0.0  0.0  13520  2352 pts/4    S+   20:03   0:00 bash -c ps au | grep yandex-disk
anton    31271  0.0  0.0   6640   820 pts/4    S+   20:03   0:00 grep yandex-disk

```

**Comment by slytomcat** [comment]
так у вас сейчас демон и не запущен.

**Comment by slytomcat** [comment]
Или он очень хорошо спрятался ....

**Comment by antohami** [comment]
```
ps aux | grep yandex-disk
anton    26846  0.1  1.0 783884 83112 pts/0    Sl+  17:20   0:14 python3 /usr/bin/yandex-disk-indicator
anton    26892  0.0  0.1 808196 13464 ?        Ssl  17:20   0:04 /usr/bin/yandex-disk --tag="7 8 9 12 15 16 19" --proxy="no" --no-daemon="true" --dir="/home/anton/Yandex.Disk" --config="/home/anton/.config/yandex-disk/config.cfg" --auth="/home/anton/.config/yandex-disk/passwd"
anton    31576  0.0  0.0   8260   764 pts/6    S+   20:10   0:00 grep yandex-disk
```

**Comment by antohami** [comment]
```
[anton@comp-e2-1800 ~]$ env -i bash -c "ps aux | grep yandex-disk"
anton    26846  0.1  1.0 783884 83116 pts/0    Sl+  17:20   0:14 python3 /usr/bin/yandex-disk-indicator
anton    26892  0.0  0.1 808196 13464 ?        Ssl  17:20   0:04 /usr/bin/yandex-disk --tag="7 8 9 12 15 16 19" --proxy="no" --no-daemon="true" --dir="/home/anton/Yandex.Disk" --config="/home/anton/.config/yandex-disk/config.cfg" --auth="/home/anton/.config/yandex-disk/passwd"
anton    31706  0.0  0.0  13520  2484 pts/6    S+   20:14   0:00 bash -c ps aux | grep yandex-disk
anton    31708  0.0  0.0   6640   764 pts/6    S+   20:14   0:00 grep yandex-disk
```

**Comment by slytomcat** [comment]
а 
`env -i LANG='en_US.UTF8' yandex-disk status `
?

**Comment by slytomcat** [comment]
У меня все-таки ощущение что демон у вас вываливается как-то сам. Логи смотрели?

**Comment by antohami** [comment]
```
env -i LANG='en_US.UTF8' yandex-disk status
Error: daemon not started
```

Зато:
```
env LANG='en_US.UTF8' yandex-disk status
Synchronization core status: idle
Path to Yandex.Disk directory: '/home/anton/Yandex.Disk'
	Total: 10 GB
	Used: 2.71 GB
	Available: 7.29 GB
	Max file size: 10 GB
	Trash size: 0 B

Last synchronized items:
	file: 'Запись экрана 2016-12-18 19:41:38.mp4'
	file: 'Включаем управление яркостью.mp4'
	file: 'Screencast_23.03.2015_08:41:30.webm'
	file: 'Screencast_23.03.2015_08:34:16.webm'
	file: 'Загрузки/Builder-icex/regular-builder-icex-20151002-x86_64.iso'
	file: 'Загрузки/Builder-icex/regular-builder-icex-qtcreator-20151005-x86_64.iso'
	file: 'Загрузки/EPIC_FLAG.rar'
	file: 'trikStudio/trikStudio-p7-64.tar.gz'
	file: 'Загрузки/FLProg_1_10_Linux64.tar.gz'
	file: 'Загрузки/Nokia N900 RX-51 Gr.RUS_sw-20.2010.36.2.exe'

```

**Comment by antohami** [comment]
А где логи лежат яндекс диска?

**Comment by slytomcat** [comment]
В .sync в синхронизируем каталоге, ну и dmesg тоже стоит с хвоста посмотреть...

**Comment by antohami** [comment]
Нет никаких ошибок, в логах всё в порядке. Не падает он.

**Comment by antohami** [comment]
А что у вас выдаёт:
`env -i LANG='en_US.UTF8' env`

**Comment by slytomcat** [comment]
Тогда у меня пока нет идей... :(

Делать сначала замену локали в текущем окружении, спрашивать статус и менять обратно - не правильное решение хотя бы еще и потому, что у меня есть там прерывания по таймеру и может статься что поменянное окружение вылезет не там где нужно.

Пускать в непустом окружении - опасно т.к. на выбор языка у яндексов каждый раз новые переменные отвечают (после того как я их отругал что они LC_CTYPE использовали, они сначала на LC_MESSAGES, а в последней версии они стали только на LANG реагировать). Только установка одной LANG дает предсказуемый результат с любой их версией.

**Comment by slytomcat** [comment]
Во есть одна: попробуйте более свежий yandex-disk поставить - у меня стоит версия 0.1.5.978. Может глюк и пройдет.

**Comment by slytomcat** [comment]
```
$ env -i LANG='en_US.UTF8' env
LANG=en_US.UTF8
```

... может так попробовать
`env -i LANG='en_US.UTF8' PATH=$PATH yandex-disk status`

**Comment by antohami** [comment]
Вот так работает:
```
env -i LANG='en_US.UTF8' TMPDIR='/tmp/.private/anton' yandex-disk status
Synchronization core status: idle
Path to Yandex.Disk directory: '/home/anton/Yandex.Disk'
	Total: 10 GB
	Used: 2.71 GB
	Available: 7.29 GB
	Max file size: 10 GB
	Trash size: 0 B

Last synchronized items:
	file: 'Запись экрана 2016-12-18 19:41:38.mp4'
	file: 'Включаем управление яркостью.mp4'
	file: 'Screencast_23.03.2015_08:41:30.webm'
	file: 'Screencast_23.03.2015_08:34:16.webm'
	file: 'Загрузки/Builder-icex/regular-builder-icex-20151002-x86_64.iso'
	file: 'Загрузки/Builder-icex/regular-builder-icex-qtcreator-20151005-x86_64.iso'
	file: 'Загрузки/EPIC_FLAG.rar'
	file: 'trikStudio/trikStudio-p7-64.tar.gz'
	file: 'Загрузки/FLProg_1_10_Linux64.tar.gz'
	file: 'Загрузки/Nokia N900 RX-51 Gr.RUS_sw-20.2010.36.2.exe'
```

**Comment by antohami** [comment]
И вот так
`env -i LANG='en_US.UTF8' TMPDIR=$TMPDIR yandex-disk status`

Где мне что поправить в исходниках, чтоб проверить работоспособность?

**Comment by slytomcat** [comment]
У меня ровно наоборот - если ставлю TMPDIR=$TMPDIR - то не находит демона, а без установки - находит. :0

**Comment by antohami** [comment]
Будем альтовскую сборку значит патчить

**Comment by slytomcat** [comment]
В Ubuntu переменная TMPDIR не определена и демон фигачит свои темпы (каталоги с именем вида yandex-disk-ea1fda1...7050s прямо в /tmp.
Но видимо переменную TMPDIR демон любит больше чем дефолтные пути.

**Comment by slytomcat** [comment]
Вот какое вижу "универсальное" решение:
1. ищем в окружении переменную TMPDIR, если не находим то берем вместо ее значения /tmp
2. запускаем демона с указанием ему переменной TMPDIR со значением определенном на шаге 1.

**Comment by slytomcat** [comment]
Попробуйте из ветки dev взять код - я там сделал как написано выше.

**Comment by slytomcat** [comment]
погонял на виртуалках с несколькими дистрибутивами - вроде все работает как надо. Влил в мастер и опубликовал в релизе 1.9.7.

**Comment by slytomcat** [comment]
Релиз можно брать тут https://github.com/slytomcat/yandex-disk-indicator/releases/latest

**Comment by antohami** [comment]
Спасибо! Статус отображается теперь. Пакет уже в Сизифе и p8.
