### ISSUE TITLE
Нет прокрутки списка каталогов исключений

### ISSUE THREAD

**Issue by Dertosh** [slytomcat/yandex-disk-indicator#171]
Можете добавить прокрутку списка каталогов исключений? Так как у меня их больше 30.

**Comment by slytomcat** [comment]
Я посмотрю что можно сделать.

**Comment by slytomcat** [comment]
Сделал в https://github.com/slytomcat/yandex-disk-indicator/commit/2611e38004832dff4d857483936425e4aae549c3

Можно пользоваться релизом https://github.com/slytomcat/yandex-disk-indicator/releases/tag/1.9.9

Вечерком на Launchpad опубликую

**Comment by slytomcat** [comment]
Fixed

**Comment by Dertosh** [comment]
![image](https://cloud.githubusercontent.com/assets/12106592/25024553/0d24a4c4-20a7-11e7-9b0e-a1781c5ba3c3.png)
Спасибо за список, но в развернутом состоянии нижняя часть не растягивается.

**Comment by slytomcat** [comment]
Да, я в курсе. Пока не понял как сделать автоматическое растягивание и сжатие (я не гуру в графических интерфейсах, к сожалению...).

**Comment by slytomcat** [comment]
Нашел решение. Пофиксил в https://github.com/slytomcat/yandex-disk-indicator/commit/3332e432a4eecd17999dba56bba72aa2d0f99c70
