### ISSUE TITLE
indication error

### ISSUE THREAD

**Issue by Hunweibyn** [slytomcat/yandex-disk-indicator#173]
(en):
Greetings, having problem with indicator when all the files synchronized and yandex.disk daemon is idle. And there is error notification appear with error. 

Problem only with indication of error in idle mode, when syncin' everything is fine

(ru):
В момент простоя, когда не производиться синхронизация, сам индикатор весит со статусом "ошибка", и после проверки на наличие синхронизации выдает уведомление об ошибке синхронизации. 

Проблема только в сообщении "ошибка" и индикации данного сообщения. Проблемы с работоспособностью и непосредственно синхронизацией нет.

![yandex-indicator-error](https://cloud.githubusercontent.com/assets/28391654/25706395/fdd8ae32-30e8-11e7-8af3-eb210be2f043.png)

**Comment by slytomcat** [comment]
Click on the status in indicator menu and see the original output message from yandex-disk daemon. 

Usually such behavior caused by file access error from daemon side.

**Comment by Hunweibyn** [comment]
Yes, thank you for you reply and help. Problem was in long filename in one of the folders. After deletion this file - everything is fine.

**Comment by slytomcat** [comment]
I've change the error status message to show the error reason.
