### ISSUE TITLE
Поддержка Python 3.2

### ISSUE THREAD

**Issue by spvkgn** [slytomcat/yandex-disk-indicator#175]
Ubuntu 12.04 c Python 3.2.3 - не взлетит?
```
~ $ yandex-disk-indicator 
  File "/usr/bin/yandex-disk-indicator", line 7
    COPYRIGHT = 'Copyright ' + u'\u00a9' + ' 2013-2016 Sly_tom_cat'
                                       ^
SyntaxError: invalid syntax
~ $ python3 --version
Python 3.2.3
```

**Comment by slytomcat** [comment]
В 12.04 не взлетит по другой причине. Под эту версию нет pyinotify для третьего питона.
Под 12.04 могу предложить только старую версию для второго питона.

**Comment by spvkgn** [comment]
@slytomcat Этот пакет для 12.04 можно бэкпортировать из исходников от 14.04, что мной было сделано изначально, но это почему-то не помогло.
```
~ $ apt-cache policy python3-pyinotify 
python3-pyinotify:
  Установлен: 0.9.4-1build1~ubuntu12.04.1
  Кандидат:   0.9.4-1build1~ubuntu12.04.1
  Таблица версий:
 *** 0.9.4-1build1~ubuntu12.04.1 0
        100 /var/lib/dpkg/status
```

**Comment by slytomcat** [comment]
Я в своё время тоже пробовал бекпортить. Как-то кривой получилось и я забросил идею поднять на 12.04 индикатор с третьей версией питона. А со вторым питоном совместимость тянуть было уже очень напряжно. Поэтому решено было для 12.04 заморозить версию под питон 2.
Если цель стоит запустить хоть чучелом, хот тушкой'

**Comment by slytomcat** [comment]
То можно поправить в исходниках юникодные символы. Их там всего два. В той строке что ругнулось и ище в одном месте. В 3.2 вроде как букву u перед константой не поддерживает.

**Comment by slytomcat** [comment]
Хотя глянул сейчас доки - в третьем u перед строкой и не нужна... сейчас апдейтик кину - попробуйте.

**Comment by spvkgn** [comment]
@slytomcat Спасибо, последний фикс решает проблему. Но видимо для shutil.which нужен Python 3.3:
```
~ $ yandex-disk-indicator 
Traceback (most recent call last):
  File "/usr/bin/yandex-disk-indicator", line 43, in <module>
    from shutil import copy as fileCopy, which
ImportError: cannot import name which
```
Пока нагуглил [такое](https://github.com/mbr/shutilwhich) решение: `from shutilwhich import which`
С ним вроде все работает нормально.

**Comment by slytomcat** [comment]
Да, 12.04 как ни крути - тащить уже тяжело. 

Но 12.04 уже не поддерживается (до 28 Апреля был). Так что пора уже обновляться.
