### ISSUE TITLE
Индиктор для 2го аккаунта: Другой экземпляр индикатора уже запущен.

### ISSUE THREAD

**Issue by sadr0b0t** [slytomcat/yandex-disk-indicator#178]
Добрый день.

В документации написано, что yd-indicator умеет показывать синхронизацию для нескольких аккаунтов
https://github.com/slytomcat/yandex-disk-indicator/wiki/Часто-задаваемые-вопросы 

Я настроил и запустил сервис ya-disk для работы с 2мя аккаунтами (судя по выводу консоли, они оба работают). Один аккаунт с дефолтными настройками, второму передаю параметры в командной строке.

Один yandex-disk-indicator запущен с настройками по умолчанию и показывает статус синхронизации для 1го аккаунта yandex.

Пробую запустить 2й экземпляр yandex-disk-indicator с указанием пути к отдельному конфиг-файлу

~~~bash
 yandex-disk-indicator --config /home/user/.config/yd-tools/yandex-disk-indicator-acc2.conf
~~~
получаю

>Другой экземпляр индикатора уже запущен.

2й индикатор не стартует

**Comment by slytomcat** [comment]
Выйдете из первого индикатора и потом запускайте его с ключем --config.

Индикатор запускается как один единственный процесс (и второй запустить сознательно не дает) а уже в нем создаются индикаторы на панель по числу настроенных конфигураций.

**Comment by slytomcat** [comment]
Чуть дополнил описание в Wiki.

**Comment by sadr0b0t** [comment]
всё получилось, спасибо
