### ISSUE TITLE
Не открывается GUI до запуска демона

### ISSUE THREAD

**Issue by mikhailnov** [slytomcat/yandex-disk-indicator#182]
Я Яндекс.Диску символическими ссылками скормил папку с 7 ГБ исходников ядра Linux в несколкьих экземплярах, yandex-disk start висит по полчаса , потребление памяти постепенно увеличивается с 9 до 450 МБ, дальше не ждал. Через конфиг дописывание строки
```exclude-dirs="/home/user/Яндекс.Диск/Linux-Dumalogiya/packages/linux-chuwi/"```
не помогло, 
```yandex-disk start --exclude-dirs="/home/user/Яндекс.Диск/Linux-Dumalogiya/packages/linux-chuwi/"```
тоже не помогло.
Установил yd-tools, надеясь, что он поможет мне настроить исключения, однако, судя по всему, yandex-disk-indicator ждет, пока выполнится yandex-disk start, и не появляется в трее, а он у меня очень джолго запускается и не известно, запустится ли вообще, как я уже написал.

Сейчас напишу в поддержку Яндекса и дам им ссылку сюда, в целом это проблема именно ЯндексДиска, но вдруг что-то придумаете или подскажете, как настроить исключения или измените алгоритм запуска Индикатора, чтобы в таких случаях, как у меня, он помог настроить исключения.

```yandex-disk setup --exclude-dirs="/home/user/Яндекс.Диск/Linux-Dumalogiya/packages/linux-chuwi/"``` тоже вызывает запуск демона, который длится очень долго.

**Comment by linxon** [comment]
такие вещи лучше всего ложить в сжатые архивы... место сэкономите

**Comment by slytomcat** [comment]
Там в исходниках - немерянное количество мелких файлов. Такое YD переваривает (синхронизирует) часами.... Но я бы не стал использовать YD для разработческих вещей - они там режут права на исполнение и тем портят билд-каталоги.

Я перенес синхронизацию всех своих разработок в Syncthing.

А индикатор просто не сможет ничего сделать если висит yandex-disk start (он просто тоже будет висеть на этой же команде).

**Comment by mikhailnov** [comment]
Так мне не нужно синхронизировать эти исходники, я их пытаюсь добавить в исключения, но не пойму, как это сделать, либо демону пофиг на настройку. Просто у меня исходники лежат в папке, которую я хочу синхронизировать. подпапку с исходниками внутри синхронизируемой папки пытаюсь добавить в исключения.

Про обрезку прав на исполнение учту,с пасибо, не знал.

**Comment by slytomcat** [comment]
В exclude-dirs вроде как нужно относительные пути писать (относительно синхронизируемого каталога)

**Comment by mikhailnov** [comment]
Не помогает ни один из вариантов ~/.config/yandex-disk/config.cfg:
```
exclude-dirs="Linux-Dumalogiya/packages/linux-chuwi/"
exclude-dirs="./Linux-Dumalogiya/packages/linux-chuwi/"
exclude-dirs="/home/user/Яндекс.Диск/Linux-Dumalogiya/packages/linux-chuwi/"
```
Сюда написал потому, что если yd-tools умеет настраивать исключения, то он бы в теории мог помочь, не дожидаясь запуска демона (при условии, что демон согласится с тем, что исключения не нужно прожевывать).

**Comment by linxon** [comment]
в моем случае это --exclude-dirs="Downloads, Camera Uploads" (относительно корневого каталога диска)

**Comment by mikhailnov** [comment]
а ключ --exclude-dirs куда дописывается? в yandex-disk setup?

**Comment by linxon** [comment]
я все это дело настраивал в yandex-disk-indicator

**Comment by slytomcat** [comment]
Ну так можете заставить индикатор запускаться без запуска демона:

Пропишите в /home/user/.config/yandex-disk/config.cfg строчку "startonstartofindicator=false" и запускайте индикатор.

Просто индикатор по умолчанию пытается запустить демона если он не запущен (что в подавляющем большинстве случаев - корректное поведение).

**Comment by mikhailnov** [comment]
Спасибо. Индикатор дописал в конфиг:
```exclude-dirs="Linux-Dumalogiya/packages/linux-chuwi"```
Но это не помогло, демон все равно не стартует нормально, до последнего перезапуска он успел выжрать 950 МБ ОЗУ.

**Comment by slytomcat** [comment]
Подозреваю, что он все равно индексирует все (прежде чем исключить) я бы просто подождал когда он наиграется со своей индексацией... долго - да, но что поделать?

**Comment by mikhailnov** [comment]
Да уже так и делаю. Но естьв ероятность, что 6 ГБ ОЗУ не хватит)
