### ISSUE TITLE
Error: activateActions() missing 1 required positional argument: 'activate'

### ISSUE THREAD

**Issue by koftikes** [slytomcat/yandex-disk-indicator#185]
**Describe what happened with indicator:**
2018-02-02 14:10:16,933 INFO     yandex-disk-indicator v.1.9.17
2018-02-02 14:10:16,934 DEBUG    Logging level: 10
2018-02-02 14:10:16,934 ERROR    Config file read error: /home/USER/.config/yd-tools/yandex-disk-indicator.conf
2018-02-02 14:10:16,934 INFO     No config, probably it is a first run.
Traceback (most recent call last):
  File "/usr/bin/yandex-disk-indicator", line 1400, in <module>
    activateActions()
TypeError: activateActions() missing 1 required positional argument: 'activate'
**Describe steps to recreate the issue:**
$ yandex-disk-indicator -l 10
**Describe your OS (distribution, version, desktop environment):**
Ubuntu 17.10, GNOME Shell 3.26.2

**Comment by slytomcat** [comment]
Ups!
I forgot to test one case after change... and exactly that case raises the bug.....

**Comment by slytomcat** [comment]
fixed in https://github.com/slytomcat/yandex-disk-indicator/releases/tag/1.9.18

I'll publish it to Launchpad in the evening (MSK time Zone)

**Comment by koftikes** [comment]
Thank you.

**Comment by linxon** [comment]
Пиветствую! 

Кстати, в gentoo во время первого запуска индикатор подвисает на очень долгое время.
Судя по процессам он пытается запустить emerge, чтобы установить файловый менеджер. 
![screenshot_2018_02_02_17_06_51](https://user-images.githubusercontent.com/8144644/35737154-99ac1360-083b-11e8-9af6-f5765633964f.png)
Сейчас, чтобы избежать этого, мне приходяится изменять вот эти строки:
```diff
--- a/yandex-disk-indicator.py	2017-05-08 21:07:51.000000000 +0300
+++ b/yandex-disk-indicator.py	2017-09-16 22:47:48.596964782 +0300
@@ -1482,8 +1482,8 @@
   config['autostart'] = checkAutoStart(autoStartDst)
   # Setup on-screen notification settings from config value
   config.setdefault('notifications', True)
-  config.setdefault('theme', False)
-  config.setdefault('fmextensions', True)
+  config.setdefault('theme', True)
+  config.setdefault('fmextensions', False)
   config.setdefault('daemons', '~/.config/yandex-disk/config.cfg')
   # Is it a first run?
   if not config.readSuccess:
@@ -1506,8 +1506,6 @@
       except:
         logger.error('Can\'t activate indicator automatic start on system start-up')
 
-    # Activate FM actions according to config (as it is first run)
-    activateActions(config['fmextensions'])
     # Default settings should be saved (later)
     config.changed = True
```
При ключении опции "Активировать расширения для файл-менеджера" индикатор опять же зависает. В качестве файлового менеджера используется Thunar

**Comment by slytomcat** [comment]
заливаю на LP
