### ISSUE TITLE
Подвисает индикатор во время первого запуска в gentoo linux

### ISSUE THREAD

**Issue by linxon** [slytomcat/yandex-disk-indicator#186]
Пиветствую! 

В gentoo, во время первого запуска, индикатор подвисает на очень долгое время.
Судя по процессам он пытается запустить emerge, чтобы установить файловый менеджер:
![screenshot_2018_02_02_17_06_51](https://user-images.githubusercontent.com/8144644/35737154-99ac1360-083b-11e8-9af6-f5765633964f.png)

Сейчас, чтобы избежать этого, мне приходяится изменять вот эти строки:
```diff
--- a/yandex-disk-indicator.py	2017-05-08 21:07:51.000000000 +0300
+++ b/yandex-disk-indicator.py	2017-09-16 22:47:48.596964782 +0300
@@ -1482,8 +1482,8 @@
   config['autostart'] = checkAutoStart(autoStartDst)
   # Setup on-screen notification settings from config value
   config.setdefault('notifications', True)
-  config.setdefault('theme', False)
-  config.setdefault('fmextensions', True)
+  config.setdefault('theme', True)
+  config.setdefault('fmextensions', False)
   config.setdefault('daemons', '~/.config/yandex-disk/config.cfg')
   # Is it a first run?
   if not config.readSuccess:
@@ -1506,8 +1506,6 @@
       except:
         logger.error('Can\'t activate indicator automatic start on system start-up')
 
-    # Activate FM actions according to config (as it is first run)
-    activateActions(config['fmextensions'])
     # Default settings should be saved (later)
     config.changed = True
```
При включении опции "Активировать расширения для файл-менеджера" индикатор так же зависает. В качестве файлового менеджера у меня используется Thunar

**Comment by slytomcat** [comment]
Изменения ваши - это просто изменение дефолтовых настроек на первом старте и сама инициализация файловых расширений при первом старте. Это все в других ОС работает нормально....

Тут мне трудно понять как правильно это обработать.....
Но там нет установки файлового менеджера, там должна быть проверка на установленность файлового менеджера. 

Собственно код этот не мой - кто-то из контрибьюторов предложил, и я принял т.к. там по тем вещам где я могу протестировать все было логично и работоспособно.

emerge там как-то оттедектился как имеющийся в наличии в строке 1124. Видимо что-то там сделано некорректно.

Да и собственно у вас стоит какой-то пакетный менеджер или нет?

Если вы хорошо разбираетесь в gentoo то, не могли бы вы подсказать как должно правильно отработать определение пакетного менеджера и как в emerge проверить установку ФМ?

**Comment by slytomcat** [comment]
Мда... нагуглил: https://dev.gentoo.org/~zmedico/portage/doc/man/emerge.1.html

вообще нет ключей -pv :( 

Правильно будет заменить 

     `emerge -pv <FM>`

на 

     `emerge --search <FM>`

???

**Comment by linxon** [comment]
на мой взгляд, тут будет лучше не ставить файловый менеджер наперекор требованиям пользователя, а ввести некий список уже установленных файловых менеджеров в системе...

Например вот так можно узнать, какой файловый менеджер используется по умолчанию на данный момент:
```bash
~$ man xdg-mime 
~$ xdg-mime query default inode/directory
Thunar-folder-handler.desktop
```
Для конкретного случая emerge необходимы права доступа, поэтому шансы на успех установки зависит от какого пользователя был запущен индикатор (нас всех с детсва учили не пользоваться root'ом)

**Comment by slytomcat** [comment]
... а, не, вотде -p и -v есть, но они ниразу не о том что нужно....

**Comment by linxon** [comment]
@slytomcat проверил команду `emerge --search thunar` на пользователе, у которого небыло прав:
```
test1@cirno-chan /home/test1 $ emerge --search thunar
  
[ Results for search key : thunar ]
Searching...

*  app-arch/unar
      Latest version available: 1.10.1
      Latest version installed: [ Not Installed ]
      Size of files: 2 493 KiB
      Homepage:      https://unarchiver.c3.cx/
      Description:   unpacker for various archiving formats, e.g. rar v3
      License:       LGPL-2.1

*  dev-python/thunarx-python
      Latest version available: 0.3.0-r2
      Latest version installed: [ Not Installed ]
      Size of files: 296 KiB
      Homepage:      https://goodies.xfce.org/projects/bindings/thunarx-python
      Description:   Python bindings for the Thunar file manager
      License:       GPL-3

*  xfce-base/thunar
      Latest version available: 1.6.13
      Latest version installed: 1.6.13
      Size of files: 1 892 KiB
      Homepage:      https://www.xfce.org/projects/ https://docs.xfce.org/xfce/thunar/start
      Description:   File manager for the Xfce desktop environment
      License:       GPL-2 LGPL-2

*  xfce-extra/thunar-archive-plugin
      Latest version available: 0.3.1-r2
      Latest version installed: 0.3.1-r2
      Size of files: 322 KiB
      Homepage:      https://goodies.xfce.org/projects/thunar-plugins/thunar-archive-plugin
      Description:   Archive plug-in for the Thunar filemanager
      License:       LGPL-2

```

т.е. команда работает

**Comment by slytomcat** [comment]
Нет установкой ФМ индикатор не должен заниматься - он его должен найти, узнать какой он...

**Comment by linxon** [comment]
наверное, будет лучше просматривать `/var/lib/portage/world` файл, в котором хранятся все установленные пользователем пакеты в системе

**Comment by slytomcat** [comment]
У меня через ~~жо..~~ "прокси"

~$ xdg-mime query default inode/directory
exo-file-manager.desktop

**Comment by linxon** [comment]
@slytomcat сейчас я поговорю в телеграме кое с кем на этот счет

**Comment by slytomcat** [comment]
Файл /var/lib/portage/world - есть во всех дистрибутивах с emerge в качестве пакетного менеджера?

Нужен метод определения установленного ФМ не зависящий от дистрибутива, но можно сделать метод зависимый от пакетного менеджера.

**Comment by slytomcat** [comment]
> @slytomcat проверил команду emerge --search thunar на пользователе, у которого небыло прав
Так и что показала проверка?

**Comment by slytomcat** [comment]
... там ведь как сделано в строках 1111 - 1130:
Ищется установленный пакетный менеджер и задается команда проверки установленного ФМ.

Далее проверяются конкретные ФМ.

**Comment by slytomcat** [comment]
Соответственно главный вопрос:
Будет ли правильно в случае обнаружения emerge проверять наличие ФМ прсто проверкой в файле  /var/lib/portage/world ?

Нужна команда которая при условии что находит ФМ - выдает 0, не находит - не 0 (1 например).

**Comment by linxon** [comment]
> /var/lib/portage/world "не в любом" дистрибутиве есть.

Действительно. Похоже этот вариант тоже не подходит, ибо в этот файл записываются только те пакеты, которые были установлены конкретно самим пользователем.

> Так и что показала проверка?

`emerge --search <имя_пакета>` аналогична команде `apt-get search <имя_пакета>` на debian based дистрибутивах

emerge/portage, как и любой другой пакетный менеджер, используется для поиска и установки/удаления пакетов, однако по скорости он уж больно медленный. Даже если мы найдем решение, используя эту команду, индикатор все равно будет подвисать на какое-то время ожидая отклика. Альтернативных пакетных менеджеров, поставляемых по умолчанию в gentoo нет

**Comment by linxon** [comment]
Мне кажется тут нужно сделать какое-то исключение для gentoo и попробовать другие варианты. 
https://github.com/slytomcat/yandex-disk-indicator/blob/15d708a876002ce0d994b08e7992b7fc5cb82d66/yandex-disk-indicator.py#L1124

Из вариантов: либо `xdg-mime query default inode/directory` (не уверен), либо парсить каталоги в /var/db/pkg/, в котором содержится список установленных пакетов отсортированных по категориям типа:
```
/var/db/pkg/net-misc/yandex-disk-0.1.5.978_p1/
/var/db/pkg/www-client/firefox-58.0.1/
/var/db/pkg/xfce-base/thunar-1.6.13/
```
 В gentoo так же существует утилита `eix` (https://wiki.gentoo.org/wiki/Eix), которую пользователи используют взамен команде `emerge --search`

Эта команда умеет выводит список всех установленных пакетов в системе:
```bash
~$ eix -I
[I] app-accessibility/at-spi2-atk
     Доступные версии:      (2) 2.22.0 2.24.1
       {test ABI_MIPS="n32 n64 o32" ABI_PPC="32 64" ABI_S390="32 64" ABI_X86="32 64 x32"}
     Установленные версии:  2.24.1(2)(14:40:03 18.01.2018)(-test ABI_MIPS="-n32 -n64 -o32" ABI_PPC="-32 -64" ABI_S390="-32 -64" ABI_X86="64 -32 -x32")
     Домашняя страница:     https://wiki.gnome.org/Accessibility
     Описание:              Gtk module for bridging AT-SPI to Atk

[I] app-accessibility/at-spi2-core
     Доступные версии:      (2) 2.22.1 2.24.1
       {X +introspection ABI_MIPS="n32 n64 o32" ABI_PPC="32 64" ABI_S390="32 64" ABI_X86="32 64 x32"}
     Установленные версии:  2.24.1(2)(14:39:43 18.01.2018)(X introspection ABI_MIPS="-n32 -n64 -o32" ABI_PPC="-32 -64" ABI_S390="-32 -64" ABI_X86="64 -32 -x32")
     Домашняя страница:     https://wiki.gnome.org/Accessibility
     Описание:              D-Bus accessibility specifications and registration daemon

[I] app-accessibility/onboard [1]
     Доступные версии:      (~)1.4.1^m {PYTHON_TARGETS="python3_4 python3_5"}
     Установленные версии:  1.4.1^m(15:05:44 30.11.2017)(PYTHON_TARGETS="python3_5 -python3_4")
     Домашняя страница:     https://launchpad.net/onboard
     Описание:              Onscreen keyboard for everybody who can't use a hardware keyboard

[I] app-admin/apache-tools
     Доступные версии:      2.2.34^t 2.4.27^t ~2.4.28^t ~2.4.29^t {libressl ssl}
     Установленные версии:  2.4.27^t(12:16:50 19.07.2017)(ssl -libressl)
     Домашняя страница:     https://httpd.apache.org/
     Описание:              Useful Apache tools - htdigest, htpasswd, ab, htdbm
```

**Comment by slytomcat** [comment]
Ну пока исключения по дистрибутивам не совсем понятно как делать - их может набраться в количестве....

А вот искать ФМ командой устанавливаемой на основе найденного пакетного менеджера - это выглядит разумным....

**Comment by linxon** [comment]
>>/var/lib/portage/world "не в любом" дистрибутиве есть.

>Действительно. Похоже этот вариант тоже не подходит, ибо в этот файл записываются только те пакеты, которые были установлены конкретно самим пользователем.

файловые менеджеры обычно состоят в зависимостях meta пакетов (xfce-base/xfce4-meta), которые устанавливают целиком DE

Еще один вариант пользователям gentoo выводить сообщение "установи nautilus"

**Comment by slytomcat** [comment]
да не, навязывать ФМ индикатором - это не здравая мысль.

**Comment by slytomcat** [comment]
Да и люди часто ставят тот ФМ что им нравится, а не тот, что с мета-пакетом им пришел.

**Comment by slytomcat** [comment]
Как грубый воркараунд можно убрать попытку определить emerge, тогда активация файловых расширений не будет осуществляться индикатором вообще на тех дистрибутивах где используется emerge. Но хоелось бы не обделять так грубо всех у кого стоит emerge....

**Comment by slytomcat** [comment]
Но самое печальное - мне просто не когда заниматься установкой gentoo что бы самому разобраться как там правильнее всего найти какой у пользователя FM установлен... :(

**Comment by slytomcat** [comment]
В Ubuntu проверка делается через dpkg -s :

```
$ dpkg -s thunar
Package: thunar
Status: install ok installed
Priority: optional
Section: xfce
Installed-Size: 890
Maintainer: Xubuntu Developers <xubuntu-devel@lists.ubuntu.com>
Architecture: amd64
Version: 1.6.11-0ubuntu0.16.04.2
Replaces: thunar-data (<< 1.2.3-3)
Depends: libatk1.0-0 (>= 1.12.4), libc6 (>= 2.4), libcairo2 (>= 1.6.0), libdbus-1-3 (>= 1.9.14), libdbus-glib-1-2 (>= 0.88), libexo-1-0 (>= 0.10.0), libgdk-pixbuf2.0-0 (>= 2.22.0), libglib2.0-0 (>= 2.37.3), libgtk2.0-0 (>= 2.24.0), libgudev-1.0-0 (>= 146), libice6 (>= 1:1.0.0), libnotify4 (>= 0.7.0), libpango-1.0-0 (>= 1.14.0), libsm6, libthunarx-2-0 (>= 1.1.0), libxfce4ui-1-0 (>= 4.9.1), libxfce4util7 (>= 4.9.0), libxfconf-0-2 (>= 4.6.0), thunar-data (= 1.6.11-0ubuntu0.16.04.2), desktop-file-utils, shared-mime-info, exo-utils
Recommends: dbus-x11, xfce4-panel (>= 4.11), xfce4-panel (<< 4.13), thunar-volman, tumbler, xdg-user-dirs, gvfs
Suggests: thunar-archive-plugin, thunar-media-tags-plugin
Breaks: thunar-data (<< 1.2.3-3)
Description: File Manager for Xfce
 Thunar is the file manager designed to be the default file manager for the
 Xfce desktop environment. It has been designed to be fast and easy to use.
 .
 Also included is an Xfce panel plugin which can manage the desktop trash.
Homepage: http://thunar.xfce.org
Original-Maintainer: Debian Xfce Maintainers <pkg-xfce-devel@lists.alioth.debian.org>
$ echo $?
0
stc@stc-w:~/DEV/YD-tools$ dpkg -s nautilus
dpkg-query: пакет «nautilus» не установлен, информация о нём недоступна
Для проверки файлов архивов используйте команду dpkg --info (dpkg-deb --info),
для вывода списка файлов в них — команду dpkg--contents (dpkg-deb --contents).
$ echo $?
1
```

**Comment by slytomcat** [comment]
надо подобрать что-то на замен dpkg -s в Portage-based дистрибутивах.....

**Comment by linxon** [comment]
> Как грубый воркараунд можно убрать попытку определить emerge, тогда активация файловых расширений не будет осуществляться индикатором вообще

думаю, с этим пока не стоит торопиться. Я тут параллельно разговариваю с товарищами... быть может еще питонист найдется

кстати как насчет команды `whereis`?
```bash
~$ whereis thunar
thunar: /usr/bin/thunar
```

**Comment by linxon** [comment]
или лучше вот эту 

```bash
which thunar || echo $?
```

**Comment by slytomcat** [comment]
Тут питон - не при делах - я там питоном пускаю команды баша для всех таких дел связанных с ФМ.

А вот с which/whereis - идеи не плохие.....

**Comment by slytomcat** [comment]
whereis - не подходит - он кучу всего ненужного находит....

а вот which - вроде неплохо справляется.

Что за коды возвратов у вас будут на 
```
which thunar; echo $?
which nautilus; echo $?
which nemo; echo $?
which dolphin; echo $?
which pantheon-files; echo $?
```
?

**Comment by linxon** [comment]
> Что за коды возвратов у вас будут на

В случае, если команда вернула ошибки, код возврата будет 1 или более
это так же касается команды **`which`**:
```bash
~$ which thunar
/usr/bin/thunar
~$ echo $?
0
~$
~$ which nautilus
which: no nautilus in (/usr/x86_64-pc-linux-gnu/gcc-bin/6.4.0:/usr/lib/llvm/5/bin:/usr/local/bin:/usr/bin:/bin:/opt/bin)
~$ echo $?
1
```

**Comment by pzskc383** [comment]
привет.

вообще говоря, может превентивно ставить плагины под все файловые менеджеры сразу?
надоест пользователю гном, поставит он мате, а тут оп — и яндекс.диск весь из себя работает. и кода меньше дебажить надо будет.

(мимо проходил)

**Comment by slytomcat** [comment]
@pzskc383 не это как-то грубо и топорно... при том то там надо еще будет кучу путей насоздавать для тех ФМ которых нет в системе.... Ну и потом - найдутся люди которым надо будет еще сотня ФМ ну пришлют пулл реквесты - отказывать не стану, а вот все это барахло всем сразу ставить - не умно будет не разу.

Уже сейчас есть расширения для 5 ФМ...

**Comment by slytomcat** [comment]
@linxon ну давайте тогда прямо сейчас в мастер запулю обновление с which для emerge? а вы попробуйте и скажите - нормально так или нет.

**Comment by linxon** [comment]
@slytomcat окей

**Comment by slytomcat** [comment]
пробуй.

**Comment by linxon** [comment]
нет. не работает :(

пытаюсь нажимать на флажок "Активировать расш.." — в thunar ничего не меняется

```bash
~$ yandex-disk-indicator 

(yandex-disk-indicator.py:7020): Gdk-CRITICAL **: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
Traceback (most recent call last):
  File "<string>", line 1091, in onButtonToggled
NameError: name 'notify' is not defined
Traceback (most recent call last):
  File "<string>", line 1091, in onButtonToggled
NameError: name 'notify' is not defined
```

**Comment by Zirrald** [comment]
Ведьму лучше на `which` заменить 👍 

https://github.com/slytomcat/yandex-disk-indicator/blob/2c7059e43622d839ad5b119492d3494493650a6c/yandex-disk-indicator.py#L1126

**Comment by slytomcat** [comment]
вот же блин. моя любимая опечатка в английском :)

**Comment by slytomcat** [comment]
пофиксил ведьму :)

**Comment by slytomcat** [comment]
Да, еще, thunar сразу файловые расширения не подхватывает, приходится его перегружать. А в крыске у меня так вообще разлогиниваться надо что бы он их подхватил :(

**Comment by linxon** [comment]
@slytomcat теперь работает

**Comment by slytomcat** [comment]
Пошел публиковать...
