### ISSUE TITLE
[Not critical] Выполнять операции в потоке

### ISSUE THREAD

**Issue by linxon** [slytomcat/yandex-disk-indicator#188]
Недавно открыл для себя такую вещь, как [потоки](https://www.ibm.com/developerworks/ru/library/l-python_part_9/). Может быть пришло время их использовать?

Дело в том, что в некоторых случаях, например, после длительного неиспользования и последующего запуска — индикатор ненадолго подвисает (не вызывается контекстное меню, как минимум). Судя по всему он ожидает ответа от **yandex-disk** демона, когда тот испытывает долгое сканирование структуры файлов в облаке и, как я понял, время ожидания растягивается до тех пор, пока демон не решит свои задачи. Были случаи, когда из-за этого у меня полностью зависала панель (xfce4-panel)

На мой взгляд использование потоков решит эту проблему, если индикатор будет запускать дополнительный процесс, когда как основной процесс будет уведомлять пользователя об ожидании ответа от этого дополнительного процесса...

**Comment by slytomcat** [comment]
К сожалению. Ни в gtk ни в qt нельзя обновлять gui-компоненты из разных потоков. 
Я в самом начале долго боролся со всякими странными глюками когда в коде было несколько потоков. Потом перевёл все на работу из главного потока и глюки пропали.

Безусловно можно реализовать разделение: главный поток занимается только обновлением gui, а с демоном yandex-disk общается другой поток/-и.

Но это потребует довольно значительных переделок.

Надо будет посмотреть на сколько заморочно это будет реализовать...

**Comment by slytomcat** [comment]
Попробуйте этот код: https://raw.githubusercontent.com/slytomcat/yandex-disk-indicator/Threading/yandex-disk-indicator.py

Можно просто скопировать этот код в /usr/bin/yandex-disk-indicator (должен быть исполняемым) и запустить как обычно.

В коде изменил:

1. Обновления демона отслеживаются через iNotify вотчер в отдельном потоке и таймер в еще одном потоке.
2. все обновления GUI делаются через добавление действия в очередь главного цикла GTK (т.е. все обновление GUI делается исключительно потоком главного цикла GTK)
3. В отдельном потоке запускается запрос на получение сообщения демона (выводится в отдельном окне), а также в индивидуальных потоках исполняются запуск и останов демона.

Возможно где-то еще нужны блокировки для критических секций, но на первый взгляд индикатор работает как раньше. Что уже хорошо (не удалось сломать, вроде как :) )

**Comment by slytomcat** [comment]
Но на время сканирования файловой системы демон не подвешивает индикатор. Там просто отдатеся статус "index".

Другое дело старт демона - там да там блокирует пока он не запустится.... а это иногда может потребовать приличного времени...

**Comment by slytomcat** [comment]
Вообщем эксперименты показали что многопоточность мало что добавляет на моих машинах, однако почему бы ей не быть. Пусть будет. выпущу в релизе 1.10.0 многопоточную версию.

На данный момент экспериментальная ветка Threading влита в мастер, заодно унифицировал и синхронизировал по кодам ветки master и gtk+qt (это заготовка на версию индикатора поддерживающую и QT и GTK, только когда оно будет - лучше не спрашивать).
