### ISSUE TITLE
Как добавить репозиторий в Parrot Linux?

### ISSUE THREAD

**Issue by maxpostal** [slytomcat/yandex-disk-indicator#189]
Как добавить репозиторий в Parrot Linux?

**Comment by slytomcat** [comment]
Вроде гугл пишет что это дистрибутив на основе debain. С-но добавляйте как в ubuntu/debian (ppa с launchpad)

**Comment by maxpostal** [comment]
При добавлении появляются ошибки:

┌─[max@parrot]─[~]
└──╼ $sudo add-apt-repository ppa:slytomcat/ppa
[sudo] password for max: 
Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 95, in <module>
    sp = SoftwareProperties(options=options)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 109, in __init__
    self.reload_sourceslist()
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 599, in reload_sourceslist
    self.distro.get_sources(self.sourceslist)    
  File "/usr/lib/python3/dist-packages/aptsources/distro.py", line 93, in get_sources
    (self.id, self.codename))
aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for Parrot/stable

**Comment by maxpostal** [comment]
Вот это смущает: could not find a distribution template for Parrot/stable
Может нужно добавить в репозитории поддержку Parrot?

p. s. заранее прошу прощения за нубский вопрос.

**Comment by maxpostal** [comment]
В общем добавил репозиторий для Ubuntu, стал ругаться на ключ, выполнил:
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys D3F70009E9DD65EA
И далее все встало. Спасибо.

**Comment by slytomcat** [comment]
Да не за что.
