### ISSUE TITLE
v.1.10.0 utilizes one CPU core up to 100% 

### ISSUE THREAD

**Issue by slytomcat** [slytomcat/yandex-disk-indicator#191]
V.1.10.0 have the issue with CPU utilization due to switch to ThreadedNotifier without any tuning.

ThreadedNotifier must be tuned properly.

**Comment by antonsoroko** [comment]
@slytomcat 
Do you plan to release a new version with this fix? I do not really want to upgrade to version with bug :-)

**Comment by slytomcat** [comment]
I hope the new release well be availibly on Launchpad in 2-4 hours.

**Comment by slytomcat** [comment]
1.10.1 published (with fix #191) on launchpad and on github.
