### ISSUE TITLE
Выборочная синхронизация через GUI

### ISSUE THREAD

**Issue by AiratTop** [slytomcat/yandex-disk-indicator#193]
Добавьте, пожалуйста, возможность выбирать синхронизируемые каталоги через GUI.

Я видел, что подобная возможность настройки есть в консоли и файле `config.cfg`, но это неудобно. 
Хотелось бы видеть, что мы выбираем и галочками "протыкать" синхронизируемые каталоги (соответственно, оставшиеся будут добавлены в исключения). 

Вот пример похожего функционала в клиенте Dropbox (v48.3.57) на Ubuntu 16.04

**Настройки синхронизации:**
![dx](https://user-images.githubusercontent.com/4050715/39082412-560acb92-456c-11e8-91cd-53c90e43742f.png)
**Выбор папок для синхронизации:**
![image](https://user-images.githubusercontent.com/4050715/39082415-6643ad4e-456c-11e8-95c1-d03c2c3b1f71.png)

**Comment by slytomcat** [comment]
А чем так сильно не устраивает существующий функционал по добавлению исключений в GUI?
![screenshot_2018-04-21_12-38-01](https://user-images.githubusercontent.com/8654729/39082862-a42c8838-4562-11e8-9bb3-4ab89ca07cd1.png)

**Comment by linxon** [comment]
индикатор умеет добавлять исключения.
Если на диске не так много директорий, то можно убрать лишнее и оставить нужное

**Comment by slytomcat** [comment]
... Нет, я не спорю, интерфейс с галочками - гораздо более интуитивно-понятный, однако я такой интерфейс около недели пытался "выпилить" и в конце концов сделал просто работу со списком исключений и стандартным диалогом выбора файлов (в режиме выбора каталогов).

Но самое печальное, что времени эта фича от'ела море, а нужна она единицам.... Плюс её даже сделанную не находят те, кому она нужна....

**Comment by AiratTop** [comment]
@slytomcat 
А что если с таким же функционалом, как есть сейчас в индикаторе, добавить возможность добавлять синхронизируемые каталоги? 
Т.е. противоположность исключениям. 
Т.е., например, нужна только одна папка, а там их куча, и придется все добавлять в исключения.

**Comment by slytomcat** [comment]
Если одну папку из кучи синхронизировать, то просто настрой демона только ее синхронизировать указав ее как корневую папку синхронизации. Какой смысл выбирать для синхронизации всю помойку а потом исключениями оставлять только одну под-паку?
Собственно сам демон умеет только с исключениями работать.

**Comment by AiratTop** [comment]
Ладно, в принципе, жить можно :)
Чет я в начале не особо рассматривал существующий механизм исключений в GUI 
Тикет можно закрыть, если он не нужен и не планируется для внедрения.

**Comment by AiratTop** [comment]
Может добавить множественный выбор папок (зажимая Ctrl) при добавлении исключений? 
Там только по одной папке добавляется, я смотрю

**Comment by slytomcat** [comment]
То что по одному - это поведение стандартного диалога выбора по умолчанию. Как там настроить множественный выбор (и можно-ли) - я не разбирался.

Собственно если есть желание - можете сами переделать на красивый интерфейс с галочками или допилить множественный выбор. Я сейчас не слишком много времени могу посвящать этому проекту и уж тем более тратить его на поддержку редко-используемых фич - не хочется.

Тут вот была идея сделать QT версию, и под это дело было уже очень много перелопачено в коде (что бы сократить объем дублирующегося кода в двух версиях индикатора), но человек, который проявил интерес сделать это, куда-то запропал - просто перестал отвечать :(.

**Comment by AiratTop** [comment]
> Собственно если есть желание - можете сами переделать на красивый интерфейс с галочками или допилить множественный выбор. 

Посмотрим, может руки дойдут.

> Тут вот была идея сделать QT версию, и под это дело было уже очень много перелопачено в коде (что бы сократить объем дублирующегося кода в двух версиях индикатора), но человек, который проявил интерес сделать это, куда-то запропал - просто перестал отвечать :(.

А есть репозиторий этой версии?

**Comment by slytomcat** [comment]
> А есть репозиторий этой версии?

Есть отдельная ветка (https://github.com/slytomcat/yandex-disk-indicator/tree/gtk+qt), где код разделен на 3 файла, так чтобы только в одном из них допиливать GUI.

**Comment by slytomcat** [comment]
С множественным выбором оказалось все просто допилили в отдельной ветке и влил в мастер https://github.com/slytomcat/yandex-disk-indicator/commit/063d86eedca0779bbf0d76fbcf379e8f657a8766.

Фича появится в следующем релизе.

**Comment by AiratTop** [comment]
О, это хорошо. Я уже обновился, всё работает, спасибо!
