### ISSUE TITLE
Подвисает во время обновления истории загрузок...

### ISSUE THREAD

**Issue by linxon** [slytomcat/yandex-disk-indicator#197]
Если во время синхронизации открыть пункт "Последние синхронизированные" и дождаться обновления списка истории, то в момент обновления индикатор насмерть зависает.

**До:** ![menu_189](https://user-images.githubusercontent.com/8144644/41658626-a58c3c02-749f-11e8-84fc-b202722cbf6a.png)

**После:** ![menu_189 1-](https://user-images.githubusercontent.com/8144644/41658759-1727e1cc-74a0-11e8-906a-f33ba67fb781.png)

**Вывод команды "yandex-disk-indicator -l10"**
```bash
2018-06-20 15:48:09,496 INFO     yandex-disk-indicator v.1.10.4
2018-06-20 15:48:09,496 DEBUG    Logging level: 10
2018-06-20 15:48:09,497 DEBUG    Config value read as: autostart = False
2018-06-20 15:48:09,498 DEBUG    Config value read as: fmextensions = False
2018-06-20 15:48:09,498 DEBUG    Config value read as: theme = True
2018-06-20 15:48:09,498 DEBUG    Config value read as: daemons = ¯\_(ツ)_/¯
2018-06-20 15:48:09,498 DEBUG    Config value read as: notifications = False
2018-06-20 15:48:09,498 INFO     Config read: ¯\_(ツ)_/¯
2018-06-20 15:48:09,555 DEBUG    Config value read as: auth = ¯\_(ツ)_/¯
2018-06-20 15:48:09,555 DEBUG    Config value read as: dir = ¯\_(ツ)_/¯
2018-06-20 15:48:09,555 DEBUG    Config value read as: exclude-dirs = ¯\_(ツ)_/¯
2018-06-20 15:48:09,555 DEBUG    Config value read as: proxy = False
2018-06-20 15:48:09,555 DEBUG    Config value read as: startonstartofindicator = False
2018-06-20 15:48:09,556 DEBUG    Config value read as: stoponexitfromindicator = True
2018-06-20 15:48:09,556 INFO     Config read: ¯\_(ツ)_/¯

(yandex-disk-indicator.py:31838): Gdk-CRITICAL **: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
2018-06-20 15:48:09,878 DEBUG    Event raised by Timer
2018-06-20 15:48:09,878 INFO     Change event: stat,size,
2018-06-20 15:48:09,880 DEBUG    Sub-menu 'Last synchronized' has 0 items
2018-06-20 15:48:09,880 INFO     Status: unknown -> none
2018-06-20 15:48:16,861 INFO     Daemon started, message: Запуск демона...Готово

2018-06-20 15:48:17,347 DEBUG    Event raised by Watcher
2018-06-20 15:48:17,347 INFO     Change event: ,,last
2018-06-20 15:48:17,450 DEBUG    Sub-menu 'Last synchronized' has 10 items
2018-06-20 15:48:24,542 DEBUG    Event raised by Watcher
2018-06-20 15:48:24,542 INFO     Change event: stat,size,
2018-06-20 15:48:24,543 INFO     Status: none -> busy
2018-06-20 15:48:59,945 DEBUG    Event raised by Watcher
2018-06-20 15:48:59,945 INFO     Change event: stat,,last
2018-06-20 15:48:59,977 DEBUG    Sub-menu 'Last synchronized' has 10 items
2018-06-20 15:49:02,185 DEBUG    Event raised by Timer
2018-06-20 15:49:02,186 INFO     Change event: stat,,
2018-06-20 15:49:04,214 DEBUG    Event raised by Timer
2018-06-20 15:49:04,215 INFO     Change event: stat,,
2018-06-20 15:49:06,252 DEBUG    Event raised by Timer
2018-06-20 15:49:06,252 INFO     Change event: stat,,
2018-06-20 15:49:12,837 DEBUG    Event raised by Timer
2018-06-20 15:49:12,838 INFO     Change event: stat,,
2018-06-20 15:49:19,326 DEBUG    Event raised by Timer
2018-06-20 15:49:19,327 INFO     Change event: stat,,
2018-06-20 15:49:23,536 DEBUG    Event raised by Timer
2018-06-20 15:49:23,536 INFO     Change event: stat,,
2018-06-20 15:49:25,843 DEBUG    Event raised by Timer
2018-06-20 15:49:25,843 INFO     Change event: stat,,
2018-06-20 15:49:31,318 DEBUG    Event raised by Timer
2018-06-20 15:49:31,318 INFO     Change event: stat,,
2018-06-20 15:49:36,524 DEBUG    Event raised by Timer
2018-06-20 15:49:36,524 INFO     Change event: stat,,
2018-06-20 15:49:41,240 DEBUG    Event raised by Timer
2018-06-20 15:49:41,240 INFO     Change event: stat,,
2018-06-20 15:49:45,907 DEBUG    Event raised by Timer
2018-06-20 15:49:45,907 INFO     Change event: stat,,
2018-06-20 15:49:51,025 DEBUG    Event raised by Timer
2018-06-20 15:49:51,025 INFO     Change event: stat,,
2018-06-20 15:49:56,252 DEBUG    Event raised by Timer
2018-06-20 15:49:56,252 INFO     Change event: stat,,
2018-06-20 15:49:59,162 DEBUG    Event raised by Timer
2018-06-20 15:49:59,162 INFO     Change event: stat,,
2018-06-20 15:50:06,320 DEBUG    Event raised by Timer
2018-06-20 15:50:06,321 INFO     Change event: stat,,
2018-06-20 15:50:13,392 DEBUG    Event raised by Timer
2018-06-20 15:50:13,393 INFO     Change event: stat,,
2018-06-20 15:50:19,664 DEBUG    Event raised by Timer
2018-06-20 15:50:19,665 INFO     Change event: stat,,
2018-06-20 15:50:26,454 DEBUG    Event raised by Timer
2018-06-20 15:50:26,454 INFO     Change event: stat,,
2018-06-20 15:50:29,859 DEBUG    Event raised by Timer
2018-06-20 15:50:29,859 INFO     Change event: stat,,
2018-06-20 15:50:37,295 DEBUG    Event raised by Timer
2018-06-20 15:50:37,295 INFO     Change event: stat,,
2018-06-20 15:50:40,419 DEBUG    Event raised by Timer
2018-06-20 15:50:40,419 INFO     Change event: stat,,
2018-06-20 15:50:45,487 DEBUG    Event raised by Timer
2018-06-20 15:50:45,488 INFO     Change event: stat,,
2018-06-20 15:50:48,635 DEBUG    Event raised by Timer
2018-06-20 15:50:48,635 INFO     Change event: stat,,
2018-06-20 15:50:52,078 DEBUG    Event raised by Timer
2018-06-20 15:50:52,079 INFO     Change event: stat,,
2018-06-20 15:50:56,290 DEBUG    Event raised by Timer
2018-06-20 15:50:56,290 INFO     Change event: stat,,
2018-06-20 15:51:01,922 DEBUG    Event raised by Timer
2018-06-20 15:51:01,922 INFO     Change event: stat,,last
2018-06-20 15:51:04,317 DEBUG    Sub-menu 'Last synchronized' has 10 items
 *** судя по всему где-то тут начинает подвисать ***
2018-06-20 15:51:07,317 DEBUG    Event raised by Timer
2018-06-20 15:51:07,317 INFO     Change event: stat,,

(yandex-disk-indicator.py:31838): Gtk-CRITICAL **: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

(yandex-disk-indicator.py:31838): Gtk-CRITICAL **: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

(yandex-disk-indicator.py:31838): Gtk-CRITICAL **: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

(yandex-disk-indicator.py:31838): Gtk-CRITICAL **: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

(yandex-disk-indicator.py:31838): Gtk-CRITICAL **: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

(yandex-disk-indicator.py:31838): Gtk-CRITICAL **: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

(yandex-disk-indicator.py:31838): Gtk-CRITICAL **: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

(yandex-disk-indicator.py:31838): Gtk-CRITICAL **: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

(yandex-disk-indicator.py:31838): Gtk-CRITICAL **: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

(yandex-disk-indicator.py:31838): Gtk-CRITICAL **: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

(yandex-disk-indicator.py:31838): Gtk-CRITICAL **: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

(yandex-disk-indicator.py:31838): Gtk-CRITICAL **: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

(yandex-disk-indicator.py:31838): Gtk-CRITICAL **: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

(yandex-disk-indicator.py:31838): Gtk-CRITICAL **: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

(yandex-disk-indicator.py:31838): Gtk-CRITICAL **: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

(yandex-disk-indicator.py:31838): Gtk-CRITICAL **: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

(yandex-disk-indicator.py:31838): Gtk-CRITICAL **: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

(yandex-disk-indicator.py:31838): Gtk-CRITICAL **: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

(yandex-disk-indicator.py:31838): Gtk-CRITICAL **: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

(yandex-disk-indicator.py:31838): Gtk-CRITICAL **: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

(yandex-disk-indicator.py:31838): Gtk-CRITICAL **: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

(yandex-disk-indicator.py:31838): Gtk-CRITICAL **: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

(yandex-disk-indicator.py:31838): Gtk-CRITICAL **: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

(yandex-disk-indicator.py:31838): Gtk-CRITICAL **: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

(yandex-disk-indicator.py:31838): Gtk-CRITICAL **: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

(yandex-disk-indicator.py:31838): Gtk-CRITICAL **: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

(yandex-disk-indicator.py:31838): Gtk-CRITICAL **: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

(yandex-disk-indicator.py:31838): Gtk-CRITICAL **: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

(yandex-disk-indicator.py:31838): Gtk-CRITICAL **: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

(yandex-disk-indicator.py:31838): Gtk-CRITICAL **: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed
2018-06-20 15:51:09,846 DEBUG    Event raised by Timer
2018-06-20 15:51:09,846 INFO     Change event: stat,,

(yandex-disk-indicator.py:31838): Gtk-CRITICAL **: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

(yandex-disk-indicator.py:31838): Gtk-CRITICAL **: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

(yandex-disk-indicator.py:31838): Gtk-CRITICAL **: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

(yandex-disk-indicator.py:31838): Gtk-CRITICAL **: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

(yandex-disk-indicator.py:31838): Gtk-CRITICAL **: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed
2018-06-20 15:51:11,926 DEBUG    Event raised by Timer
2018-06-20 15:51:11,926 INFO     Change event: stat,,
2018-06-20 15:51:14,329 DEBUG    Event raised by Timer
2018-06-20 15:51:14,329 INFO     Change event: stat,,
2018-06-20 15:51:22,086 DEBUG    Event raised by Timer
2018-06-20 15:51:22,086 INFO     Change event: stat,,
2018-06-20 15:51:25,687 DEBUG    Event raised by Timer
2018-06-20 15:51:25,687 INFO     Change event: stat,,
2018-06-20 15:51:33,342 DEBUG    Event raised by Timer
2018-06-20 15:51:33,342 INFO     Change event: stat,,
2018-06-20 15:51:37,245 DEBUG    Event raised by Timer
2018-06-20 15:51:37,245 INFO     Change event: stat,,
2018-06-20 15:51:42,633 DEBUG    Event raised by Timer
2018-06-20 15:51:42,633 INFO     Change event: stat,,
2018-06-20 15:51:47,837 DEBUG    Event raised by Timer
2018-06-20 15:51:47,838 INFO     Change event: stat,,
*** Делаю SIGTERM ***
2018-06-20 15:51:49,586 DEBUG    Exit started
2018-06-20 15:51:49,586 DEBUG    Indicator exit started: 
2018-06-20 15:51:58,573 INFO     Daemon stopped, message: Демон остановлен.

2018-06-20 15:51:58,573 INFO     Demon stopped
2018-06-20 15:51:58,573 DEBUG    Indicator exited
```

Пугают сообщения "(yandex-disk-indicator.py:31838): Gtk-CRITICAL **"...
ОС Gentoo Linux. Дерево зависимостей:
```bash
* dependency graph for x11-misc/yd-tools-1.10.4
 `--  x11-misc/yd-tools-1.10.4  ~amd64 
   `--  dev-lang/python-3.4.8  (dev-lang/python) amd64 
   `--  dev-lang/python-3.5.5  (dev-lang/python) amd64 
   `--  dev-lang/python-3.6.5  (dev-lang/python) amd64 
   `--  dev-lang/python-exec-2.4.5  (>=dev-lang/python-exec-2) amd64  [python_targets_python3_4(-)? python_targets_python3_5(-)? python_targets_python3_6(-)? -python_single_target_python3_4(-) -python_single_target_python3_5(-) -python_single_target_python3_6(-)]
   `--  dev-libs/glib-2.52.3  (>=dev-libs/glib-2.0) amd64 
   `--  dev-libs/libappindicator-12.10.0-r301  (dev-libs/libappindicator) amd64 
   `--  dev-python/pyinotify-0.9.6  (>=dev-python/pyinotify-0.9.6) amd64  [python_targets_python3_4(-)? python_targets_python3_5(-)? python_targets_python3_6(-)? -python_single_target_python3_4(-) -python_single_target_python3_5(-) -python_single_target_python3_6(-)]
   `--  dev-python/pygobject-3.24.1  (dev-python/pygobject) amd64  [python_targets_python3_4(-)? python_targets_python3_5(-)? python_targets_python3_6(-)? -python_single_target_python3_4(-) -python_single_target_python3_5(-) -python_single_target_python3_6(-)]
   `--  gnome-extra/zenity-3.24.0  (gnome-extra/zenity) amd64 
   `--  net-misc/yandex-disk-0.1.5.978_p1  (net-misc/yandex-disk) ~amd64 
   `--  x11-misc/xclip-0.13  (x11-misc/xclip) amd64 
   `--  x11-libs/gtk+-3.22.29  (>=x11-libs/gtk+-3.0) amd64 
   `--  x11-libs/gdk-pixbuf-2.36.12  (>=x11-libs/gdk-pixbuf-2.0) amd64 
   `--  sys-devel/gettext-0.19.8.1  (sys-devel/gettext) amd64 
   `--  sys-apps/sed-4.2.2  (>=sys-apps/sed-4) amd64 
[ x11-misc/yd-tools-1.10.4 stats: packages (16), max depth (1) ]
```

**Comment by slytomcat** [comment]
По "Gtk-CRITICAL **: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed" гуглится довольно много багрепортов, но все - в довольно далеком прошлом... И в части решались обновлениями.

Воспроизвести такое у себя на машине - не удалось. 

Т.е. скорее всего, траблы где-то в конкретной версии GTK. 

Обновление Last synchronized - я довольно давно не менял. И последний раз, когда менял, пилили код как можно более безопасный ибо с этим подменю уже были глюки разные, уходящие корнями тоже в GTK.

... прямо сейчас, на первый взгляд, мыслей "куда копать" - пока нет....
Будем думать....

**Comment by slytomcat** [comment]
А попробуйте код из dev ветки - я там лишний раз .show() дернул при обновлении. 
Не уверен что поможет, но давайте пробовать разное, может и найдем решение без обновления GTK.

**Comment by linxon** [comment]
> я там лишний раз .show() дернул

К сожалению не помогло..
Кстати, нашел интересные коментарии по этому поводу: https://bugzilla.redhat.com/show_bug.cgi?id=856682#c15

**Comment by linxon** [comment]
https://github.com/slytomcat/yandex-disk-indicator/commit/cbe83bf012ce74ad0aeea87c9463b57066fbf00e — основное меню и сабменю дестроятся после чего обратно не появляются. Зато теперь не зависает :) 
думаю можно оставить дестрой как временное решение...

**Comment by slytomcat** [comment]
А если вариант №2 - с явным дестроем?

**Comment by slytomcat** [comment]
А после этого заново открыть дает?

**Comment by slytomcat** [comment]
... странно что основное меню дестроится.... там же дестрой только субменю вызывается....

Собсвенно, как показал мой опыт: меню в GTK не очень любят всякую динамику. Глюки все вылезают именно при обновлении меню. Создается такое впечатление что разрабы слегка подзабивают на динамику т.к. 99% меню - статичные.

**Comment by linxon** [comment]
> А после этого заново открыть дает?

ага!

Ну я даже пробовал менять темы оформления для GTK3 — не помогло. Может это особенности gtk версии `3.22.29`. Чуть позже попробую обновиться до `3.22.30`

P.S.
Похоже эта проблема была пофикшена в `3.22.30`:
https://gitlab.gnome.org/GNOME/gtk/issues/83
https://ftp.gnome.org/pub/gnome/sources/gtk+/3.22/gtk+-3.22.30.news
> \* Bugs fixed:
  #28 Adwaita: Selection mode styling flickers
  **#83Completion popup on non-default GdkDisplay freezes GtkFileChooserDialog**
  #88 GtkSpinButton: Buttons aren't de/sensitised as they were in GTK+ 3
 #114 All Wayland apps crash when focused (gtk_gesture_multi_press_endв†’...
 #129 Segfault in `wl_proxy_marshal()`
.......

Может быть и на питоне можно как-то получить конкретную версию используемой gtk, чтобы сделать условие на проверку? Если да, то я попробую обновиться до `3.22.30` и протестить.

**Comment by linxon** [comment]
> можно как-то получить конкретную версию используемой gtk, чтобы сделать условие на проверку

имею ввиду для того, чтобы обойти эту проблему в `3.22.29`

**Comment by linxon** [comment]
> попробую обновиться до 3.22.30 и протестить

Увы, не помогло! 

Что я заметил:
Ошибка `Gtk-CRITICAL **: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed` появляется во время движения курсора мыши по экрану. Как только индикатор зависнит, то и вместе с ним все так же зависает весь десктоп, из-за чего я не могу взаимодействовать с окнами, открыть меню, использовать горячие клавиши. Приходится переходить в TTY :(

**Comment by linxon** [comment]
А как себя чувствует qt версия индикатора?

**Comment by slytomcat** [comment]
Gtk-CRITICAL - 'CRITICAL' как бы намекает... После этой ошибки там основной цикл GTK подвисает и приходит хана всему GUI. Народ на стаковерфлове только одно и обсуждает - как заставить GTK игнорировать эту ошибку. И рецепты там есть. Но это ИМХО не совсем верный вариант... Надо бы устранить причину по которой этот критикал возникает.

Qt версию на питоне взялся сделать один человек. Я разделил проект на две аля-мастер ветки и сейчас все обновления коммичу в обе. Кроме текущего мастера есть ветка gtk+qt в которой код индикатора разделен на три части - тулзы, наблюдатель за yandex-disk, и GUI. Идея такова, что в зависимости от того, какой GUI компонент в сборку включается получается либо GTK, либо QT версия. 
По своей части работ (размежевание GUI от всего остального) я все сделал, QT-шный GUI - пока в работе (человек работу поменял, поэтому не быстро).

**Comment by slytomcat** [comment]
... впринципе. там на QT перевести трудного ничего нет. Я и сам подумывал это сделать, но я бы хотел (чисто из соображений обеспечить проекту более надежную поддержку) чтобы в коде индикатора хорошо разобрались другие люди. И что бы они могли помогать решать проблемы и поддерживать/развивать проект. 
Пока я пилил его в одни руки - вышло так, что сейчас и яндекс и другие разрабы практически забили на индикатор для Linux т.к. есть этот. И как-то невзначай оказалось, что моя наколенная поделка используется сотнями, если не тысячами людей, и эта ответственность немного напрягает, когда ты не можешь ей с кем-то поделиться... А поделится хочется ибо мы все не вечны.

**Comment by linxon** [comment]
Приветствую! Как обстоят дела с этим багом?

Мне кажется, что все таки не стоит считать решением автоматическое скрытие меню во время обновления списка. Было замечено, что во время синхронизации мелких по размеру файлов в меню списка просто невозможно попасть. Как только начинаешь наводить курсор мыши — оно появляется и моментально исчезает.

**Comment by slytomcat** [comment]
Там нет скрытия. Там просто дестрой меню и создание нового.
По поводу очень частых обновлений при синхронизации множества мелких файлов. Интересно будет посмотреть это со старым решением (когда меню сохранялось старое, а из него все уделялось и добавлялось заново).
В целом, думаю стоит ограничить частоту обновлений этого меню. Т.е. завести таймер и пока он не истечёт обновления меню пропускать. Обновить только по таймеру.

**Comment by linxon** [comment]
>Там нет скрытия. Там просто дестрой меню и создание нового

в моем случае оно (меню со списком) просто исчезает вместе с основным меню и мне приходится снова открывать его ПКМ по трею.

**Comment by linxon** [comment]
Может быть такое происходит из-за потери фокуса, но как оказалось не имеет значения где именно находится курсор.

**Comment by slytomcat** [comment]
Надо разбираться... Дестрой меню это конечно грубо. Но вывешивание GTK критической ошибкой - это просто неприемлемо.

**Comment by revengel** [comment]
+1

**Comment by slytomcat** [comment]
@revengel, поясните подробнее что значит ваше +1

**Comment by linxon** [comment]
Приветствую!

>Gtk-CRITICAL - 'CRITICAL' как бы намекает... После этой ошибки там основной цикл GTK подвисает и приходит хана всему GUI. Народ на стаковерфлове только одно и обсуждает - как заставить GTK игнорировать эту ошибку. И рецепты там есть. Но это ИМХО не совсем верный вариант... Надо бы устранить причину по которой этот критикал возникает.

Вот тут, вроде как, попытались исправить внутреннюю ошибку https://gitlab.gnome.org/GNOME/gtk/issues/750

внизу по ссылке можно увидеть патчи для <=gtk+-3.24, которые, к сожалению, не помогают в нашем случае
```diff
From d2c9fc61cf210cc062109c4a508fb6984cf8cc8b Mon Sep 17 00:00:00 2001
From: Mohammed Sadiq <sadiq@sadiqpk.org>
Date: Wed, 9 Jan 2019 16:36:06 +0530
Subject: [PATCH] gtkpopover: Fix popover when parent widget is partially
 visible

fixes https://gitlab.gnome.org/GNOME/gtk/issues/750
---
 gtk/gtkpopover.c | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/gtk/gtkpopover.c b/gtk/gtkpopover.c
index 73a9e56974..b4746b1abe 100644
--- a/gtk/gtkpopover.c
+++ b/gtk/gtkpopover.c
@@ -1134,7 +1134,7 @@ _gtk_popover_update_child_visible (GtkPopover *popover)
     }
 
   parent = gtk_widget_get_parent (GTK_WIDGET (priv->parent_scrollable));
-  rect = priv->pointing_to;
+  gtk_popover_get_pointing_to (widget, &rect);
 
   gtk_widget_translate_coordinates (priv->widget, parent,
                                     rect.x, rect.y, &rect.x, &rect.y);
-- 
2.18.1

```

P.S.
Только что попробовал поставить latest версию `gtk+-3.24.5`, в которой теперь это меню вообще не обновляется (без патча https://github.com/slytomcat/yandex-disk-indicator/commit/cbe83bf012ce74ad0aeea87c9463b57066fbf00e). Как по мне это хороший знак :)

P.P.S
Не буду торопиться с этим выводом

**Comment by linxon** [comment]
> Только что попробовал поставить latest версию gtk+-3.24.5, в которой теперь это меню вообще не обновляется (без патча cbe83bf). Как по мне это хороший знак :)

в `gtk+-3.24.5` меню индикатора обновляется и всё так же намертво зависает :(

**Comment by slytomcat** [comment]
Мне трудно понять куда копать, если честно... 
У меня нет платформы для воспроизводства проблемы а на всем что у меня есть - эту проблему не воспроизвести. Нужно ставить в виртуалку что-то и пробовать воспроизвести. 
@linxon дадите ссылочку на какой-то образ ОС чтобы тестовую среду настроить?

**Comment by linxon** [comment]
> дадите ссылочку на какой-то образ ОС чтобы тестовую среду настроить?

могу предложить минималистичную livecd самосборку, которая имеет такую же конфигурацию, как и у меня.

Сегодня вечером попробую подготовить образ

**Comment by linxon** [comment]
Прошу прощения, что не смог управиться к выходным.
https://yadi.sk/d/1zNeEeDarbDpGA

P.S.
Если что-то будет не так, то можно попробовать поставить кальку: https://mirror.yandex.ru/calculate/release/18.12/cldx-18.12-x86_64.iso (версия с XFCE)

**Comment by slytomcat** [comment]
Да ничего страшного, даже к лучшему - у меня дома нормальная для виртуалки машина в руках подрастающего поколения (т.е. с очень ограниченным доступом для меня :) ) а на моем древнем ноуте виртуалку поднимать очень трудно....

Мне проще на работе это пробовать.

**Comment by slytomcat** [comment]
Фух вроде бы настроил кальку в VB. 
Завтра попробую с индикатором поиграться.

**Comment by konarev** [comment]
Такая же проблема на Manjaro XFCE

**Comment by linxon** [comment]
@konarev как временное решение:

```diff
diff -ur a/yandex-disk-indicator.py b/yandex-disk-indicator.py
--- a/yandex-disk-indicator.py	2018-10-22 17:23:11.000000000 +0300
+++ b/yandex-disk-indicator.py	2018-10-31 18:49:11.443968583 +0300
@@ -781,6 +781,11 @@
       # Update last synchronized sub-menu on first run or when last data has changed
       if vals['lastchg'] or vals['laststatus'] == 'unknown':
         # Update last synchronized sub-menu
+        
+        # Fix bug: https://github.com/slytomcat/yandex-disk-indicator/issues/197
+        # Temporary disable show synchronized sub menu while updating
+        self.lastItems.destroy()
+        
         self.lastItems = Gtk.Menu()                   # Create new Sub-menu:
         for filePath in vals['lastitems']:            # Create new sub-menu items
# Create menu label as file path (shorten it down to 50 symbols when path length > 50
```

**Comment by MikePooh** [comment]
Проблема имеется на Linux Mint 19.1 c окружением рабочего стола Mate основанного на GTK.

**Comment by konarev** [comment]
> @konarev как временное решение:
> 
> ```diff
> diff -ur a/yandex-disk-indicator.py b/yandex-disk-indicator.py
> --- a/yandex-disk-indicator.py	2018-10-22 17:23:11.000000000 +0300
> +++ b/yandex-disk-indicator.py	2018-10-31 18:49:11.443968583 +0300
> @@ -781,6 +781,11 @@
>        # Update last synchronized sub-menu on first run or when last data has changed
>        if vals['lastchg'] or vals['laststatus'] == 'unknown':
>          # Update last synchronized sub-menu
> +        
> +        # Fix bug: https://github.com/slytomcat/yandex-disk-indicator/issues/197
> +        # Temporary disable show synchronized sub menu while updating
> +        self.lastItems.destroy()
> +        
>          self.lastItems = Gtk.Menu()                   # Create new Sub-menu:
>          for filePath in vals['lastitems']:            # Create new sub-menu items
> # Create menu label as file path (shorten it down to 50 symbols when path length > 50
> ```

Спасибо, помогло

**Comment by slytomcat** [comment]
Вроде бы с дестроем пробовали ранее (или я уже запутался что пробовали а что нет). 

Но если помогает - добавлю в мастер.

@linxon сделаете пулл реквест с временным фиксом?

**Comment by slytomcat** [comment]
PS на работе немного завал - потестить индикатор в кальке руки так и не дошли - уперся на отсутствие зависимостей - как их поставить не успел найти...
@linxon а в вашей сборке все уже есть по зависимостям или тоже надо доставлять питоновские либы LIbAppindicator и GIR?

**Comment by linxon** [comment]
> потестить индикатор в кальке руки так и не дошли - уперся на отсутствие зависимостей - как их поставить не успел найти... 

> а в вашей сборке все уже есть по зависимостям или тоже надо доставлять питоновские либы LIbAppindicator и GIR?

`dev-libs/libappindicator` нужно собрать с флагом `introspection`, который потянет за собой `dev-libs/gobject-introspection`.

Попробуйте установить зависимости одной командой:
```bash
~$ sudo USE="introspection" emerge -a1 dev-libs/libappindicator:3 dev-python/pyinotify dev-python/pygobject:3 gnome-extra/zenity net-misc/yandex-disk x11-misc/xclip x11-libs/gdk-pixbuf:2
```

**Comment by slytomcat** [comment]
Очень долго бился с Xubuntu (XFCE/GTK+) в рамках перевода другого [своего индикатора](https://github.com/slytomcat/yd-go) на другую библиотеку показа нотификаций и уведомлений. И пришел к четкому пониманию, что в GTK как-то очень криво работает подменю. Уже не знаю где именно эта проблема закопана, но подменю может показываться через раз и как не бодайся с этим на уровне приложения - ничего не помогает.

Убил я на это понимание очень много часов. И самое обидное - не могу понять в какой проект отправлять багрепорт...

Это ишью закрываю т.к. не вижу что еще могу с ним сделать в таких условиях.
