### ISSUE TITLE
Индикатор не стартует после логаута пользователя

### ISSUE THREAD

**Issue by maxpoletaev** [slytomcat/yandex-disk-indicator#2]
Директория `/tmp` при логауте пользователя не очищается. Лок-файл `/tmp/yandex-disk-indicator.lock` не удаляется, из за чего индикатор, после повтороного входа, не может запуститься.

Дополнительно, нельзя запустить индикатор для нескольких пользователей, ибо лок-файл один на всех.

**Comment by slytomcat** [comment]
Работа с несколькими пользователями не предусматривалась в проекте изначально.

/tmp/yandex-disk-indicator.lock и не должен вычищаться при закрытии индикатора, с него только снимается эксклюзивный лок.

**Comment by slytomcat** [comment]
Многопользовательская поддержка появилас с версии 1.4.2 и теперь можно запустить сразу несколько индикаторов даже в рамках одного пользователя (соотвественно нужно настроить и несколько демонов для одного пользователя, это можно сделать прямо из индикатора запуская с ключем -с : смотри описание: yandex-disk-indicator --help)
