### ISSUE TITLE
Wrong localization info

### ISSUE THREAD

**Issue by FRiMN** [slytomcat/yandex-disk-indicator#20]
Неверное сообщение о локализации.

Код в строках [934-936](https://github.com/slytomcat/yandex-disk-indicator/blob/dev/yandex-disk-indicator.py#L934) исполняется в любом случае, даже если файл локализации не найден.
Соответственно то, что после except -- не исполняется, а текст в приложении на английском.
В консоли же сообщается неверная инфа.

Отсюда предположение о безсмысленности `_ = str`. В **gettext**'е это уже всё, вроде, автоматизировано.
Я бы поправил, но не знаю причины проверки.

**Comment by slytomcat** [comment]
Спасибо за информацию - я просто не имел возможности протестировать на платформе с неподдерживаемой локализацией (у меня везде либо english либо русский).

Собственно про бесполезность ветки с  _ = str - и всегда исполняющийся код в 935 строчке - это скорее всего недосмотр с мой стороны при очередном изменении этого кода - прото раньше там _ определялось либо в одной ветке либо в другой, я код поменял, а лишнее не подчистил...

Вывод про загруженную локализацию в терминал - собственно и не очень нужен - оно и так видно - подтянулась локализация или нет.

**Comment by slytomcat** [comment]
Ааа черт, оказывается это всегда так было в моем коде. Просто объект translation не выдает ексепшена, если передан параметр fallback=True. Я этот параметр просто не правильно понял еще когда в первый раз копал вопрос переводов.

В 1.5.1 исправлю.

**Comment by slytomcat** [comment]
Пофиксил в v.1.5.1
Релиз сделаю когда подтянутся допереведенная локаль для греческого.
