### ISSUE TITLE
Не подключается к сервису яндекс диска

### ISSUE THREAD

**Issue by n-r-w** [slytomcat/yandex-disk-indicator#200]
Manjaro Linux, Release: 18.0.0-rc, XFCE
Яндекс.Диск 0.1.5.1010

Индикатор не подключается к сервису яндекс диска и горит серым цветом. На кнопку "запустить сервис" - не реагирует. Сам яндекс-диск работает и синхронизирует нормально.

`2018-10-21 00:29:54,444 INFO     yandex-disk-indicator v.1.10.4
2018-10-21 00:29:54,444 DEBUG    Logging level: 10
2018-10-21 00:29:54,445 DEBUG    Config value read as: autostart = True
2018-10-21 00:29:54,445 DEBUG    Config value read as: notifications = False
2018-10-21 00:29:54,445 DEBUG    Config value read as: theme = False
2018-10-21 00:29:54,445 DEBUG    Config value read as: fmextensions = True
2018-10-21 00:29:54,445 DEBUG    Config value read as: daemons = /home/we/.config/yandex-disk/config.cfg
2018-10-21 00:29:54,445 INFO     Config read: /home/we/.config/yd-tools/yandex-disk-indicator.conf
/usr/bin/yandex-disk-indicator:716: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  self.last = Gtk.MenuItem(_('Last synchronized items'))
/usr/bin/yandex-disk-indicator:722: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  self.daemon_ss = Gtk.MenuItem('')         # Start/Stop daemon: Label is depends on current daemon status
/usr/bin/yandex-disk-indicator:725: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  self.open_folder = Gtk.MenuItem(_('Open Yandex.Disk Folder'))
/usr/bin/yandex-disk-indicator:728: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  open_web = Gtk.MenuItem(_('Open Yandex.Disk on the web'))
/usr/bin/yandex-disk-indicator:732: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  self.preferences = Gtk.MenuItem(_('Preferences'))
/usr/bin/yandex-disk-indicator:735: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  open_help = Gtk.MenuItem(_('Help'))
/usr/bin/yandex-disk-indicator:737: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  help1 = Gtk.MenuItem(_('Yandex.Disk daemon'))
/usr/bin/yandex-disk-indicator:740: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  help2 = Gtk.MenuItem(_('Yandex.Disk Indicator'))
/usr/bin/yandex-disk-indicator:746: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  self.about = Gtk.MenuItem(_('About'));    self.about.connect("activate", self.openAbout)
/usr/bin/yandex-disk-indicator:749: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  close = Gtk.MenuItem(_('Quit'))
2018-10-21 00:29:54,451 DEBUG    Config value read as: auth = /home/we/.config/yandex-disk/passwd
2018-10-21 00:29:54,451 DEBUG    Config value read as: dir = /home/we/Yandex.Disk
2018-10-21 00:29:54,451 DEBUG    Config value read as: proxy = False
2018-10-21 00:29:54,451 INFO     Config read: /home/we/.config/yandex-disk/config.cfg
2018-10-21 00:29:54,763 DEBUG    Event raised by Timer
2018-10-21 00:29:54,763 INFO     Change event: stat,size,
2018-10-21 00:29:54,766 DEBUG    Sub-menu 'Last synchronized' has 0 items
2018-10-21 00:29:54,766 INFO     Status: unknown -> none
/usr/bin/yandex-disk-indicator:693: DeprecationWarning: AppIndicator3.Indicator.set_icon is deprecated
  self.ind.set_icon(self.icon[status])
2018-10-21 00:29:55,630 INFO     Daemon started, message: Демон уже запущен.`

**Comment by antonsoroko** [comment]
@n-r-w
#199
Здравствуйте.
Попробуйте обновить версию до 1.10.5, кажется похоже.

**Comment by slytomcat** [comment]
Да, индикатор 1.10.4 с yandex-disk 0.1.5.1010 перестал работать. В связи с этим надо ставить индикатор 1.10.5.

Deb пакет уже лежит в ppa.
Rpm майнтейнеры altlinux обновили.
Можно ещё из исходников поставить (в обход пакетной системы) или просто один файл обновить через wget.

**Comment by slytomcat** [comment]
```
wget https://raw.githubusercontent.com/slytomcat/yandex-disk-indicator/master/yandex-disk-indicator.py -O /usr/bin/yandex-disk-indicator
chmod a+x /usr/bin/yandex-disk-indicator
```

**Comment by n-r-w** [comment]
Спасибо, а какой файл обновить? В archlinux aur все еще лежит [1.10.4](https://aur.archlinux.org/packages/yandex-disk-indicator/)

**Comment by n-r-w** [comment]
Все заработало!

**Comment by slytomcat** [comment]
что бы в Арч-е появилось обновленный пакет.  надо майинтейнеров теребить, я альтовых теребил. В альте должен быть обновленный rpm.
