### ISSUE TITLE
yd-tools require libappindicator-gtk3

### ISSUE THREAD

**Issue by torgash-ivanblch** [slytomcat/yandex-disk-indicator#201]
Say, on Manjaro Linux XFCE/MATE libappindicator-gtk3 isn't installed by default, so yandex-disk-indicator raises `ValueError: Namespace AppIndicator3 not available`
This should have been mentioned in README.md as a dependency required.

**Comment by slytomcat** [comment]
AppIndicator3 It not just one dependency that yandex-disk-indicator required. 
Full list of dependencies are in https://github.com/slytomcat/yandex-disk-indicator/blob/master/build/yd-tools/debian/control

And this is matter of maintainer of the package that you use on Manjaro Linux.

**Comment by slytomcat** [comment]
Unfortunately I haven't a contact to AUR package maintainer.

**Comment by slytomcat** [comment]
The matter is even worse: AUR package (that was available a day ago) disappeared from available AUR packages: https://aur.archlinux.org/packages/?K=yandex-disk-indicator ...

If you are trying to install yandex-disk-indicator from the sources then look at dependencies that I pointed earlier (in debian control file).

**Comment by slytomcat** [comment]
I've updated readme and wiki to warn about dependencies.

**Comment by e-pc** [comment]
> The matter is even worse: AUR package (that was available a day ago) disappeared from available AUR packages: https://aur.archlinux.org/packages/?K=yandex-disk-indicator ...

I think this happened because of the changes to the files prepare.sh, install.sh and now the building of the package requires root privileges.

**Comment by slytomcat** [comment]
I don't think so.

There is no changes in prepare.sh and install.sh files between 1.10.4 and 1.10.5. The last AUR package that I've seen was build from 1.10.4 source.

**Comment by slytomcat** [comment]
... and even more: install.sh - the script that intended only for manual installation from source (and it obviously requires root privileges) while prepare.sh is used for installation and package building, but it is used with different TARGET paths for these two different purposes. There is no need in root privileges in case of package building as TARGET is pointed to the staging folder but not to system catalogues.

**Comment by e-pc** [comment]
> I don't think so.
> 
> There is no changes in prepare.sh and install.sh files between 1.10.4 and 1.10.5. The last AUR package that I've seen was build from 1.10.4 source.

The TARGET variable is exported form from install.sh to prepare.sh and defined as 
`TARGET="/usr"`
But probably it's possible to set the target in PKGBUILD and then copy to all the necessary files 'to /usr'

**Comment by e-pc** [comment]
> There is no need in root privileges in case of package building as TARGET is pointed to the staging folder but not to system catalogues.

Don't have much experience in package building but will try to build tonight or tomorrow.

**Comment by slytomcat** [comment]
Again: instal.sh in not intended for package building. It is ONLY intended for manual installation from source.

**Comment by e-pc** [comment]
I see, thank you! I'll try to build the package as I said before and will let you know the results.

**Comment by slytomcat** [comment]
Debian package is built via build_deb.sh. And there TARGET defined as ./yd-tools/usr
