### ISSUE TITLE
Status is "Not started"

### ISSUE THREAD

**Issue by Alexander3XL** [slytomcat/yandex-disk-indicator#202]
Hi! I updated yandex-disk and status became "Not started"; "Used: .../..."
ArchLinux gnome 3
aur/yandex-disk 0.1.5.978-2 -> 0.1.5.1010-1

$ yandex-disk-indicator -l10
2018-10-30 16:23:23,178 INFO     yandex-disk-indicator v.1.10.5
2018-10-30 16:23:23,178 DEBUG    Logging level: 10
2018-10-30 16:23:23,179 DEBUG    Config value read as: autostart = True
2018-10-30 16:23:23,179 DEBUG    Config value read as: notifications = True
2018-10-30 16:23:23,179 DEBUG    Config value read as: theme = False
2018-10-30 16:23:23,179 DEBUG    Config value read as: fmextensions = True
2018-10-30 16:23:23,179 DEBUG    Config value read as: daemons = /home/alexander/.config/yandex-disk/config.cfg
2018-10-30 16:23:23,179 INFO     Config read: /home/alexander/.config/yd-tools/yandex-disk-indicator.conf
/usr/bin/yandex-disk-indicator:717: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  self.last = Gtk.MenuItem(_('Last synchronized items'))
/usr/bin/yandex-disk-indicator:723: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  self.daemon_ss = Gtk.MenuItem('')         # Start/Stop daemon: Label is depends on current daemon status
/usr/bin/yandex-disk-indicator:726: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  self.open_folder = Gtk.MenuItem(_('Open Yandex.Disk Folder'))
/usr/bin/yandex-disk-indicator:729: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  open_web = Gtk.MenuItem(_('Open Yandex.Disk on the web'))
/usr/bin/yandex-disk-indicator:733: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  self.preferences = Gtk.MenuItem(_('Preferences'))
/usr/bin/yandex-disk-indicator:736: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  open_help = Gtk.MenuItem(_('Help'))
/usr/bin/yandex-disk-indicator:738: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  help1 = Gtk.MenuItem(_('Yandex.Disk daemon'))
/usr/bin/yandex-disk-indicator:741: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  help2 = Gtk.MenuItem(_('Yandex.Disk Indicator'))
/usr/bin/yandex-disk-indicator:747: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  self.about = Gtk.MenuItem(_('About'));    self.about.connect("activate", self.openAbout)
/usr/bin/yandex-disk-indicator:750: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  close = Gtk.MenuItem(_('Quit'))
2018-10-30 16:23:23,212 DEBUG    Config value read as: proxy = False
2018-10-30 16:23:23,213 DEBUG    Config value read as: dir = /home/alexander/ahome/ydisk
2018-10-30 16:23:23,213 DEBUG    Config value read as: auth = /home/alexander/.config/yandex-disk/passwd
2018-10-30 16:23:23,213 INFO     Config read: /home/alexander/.config/yandex-disk/config.cfg
2018-10-30 16:23:23,518 INFO     Daemon started, message: Daemon is already running.

2018-10-30 16:23:23,531 DEBUG    Event raised by Timer
2018-10-30 16:23:23,532 INFO     Change event: stat,size,
2018-10-30 16:23:23,536 DEBUG    Sub-menu 'Last synchronized' has 0 items
2018-10-30 16:23:23,536 INFO     Status: unknown -> none
/usr/bin/yandex-disk-indicator:694: DeprecationWarning: AppIndicator3.Indicator.set_icon is deprecated
  self.ind.set_icon(self.icon[status])

**Comment by Alexander3XL** [comment]
Нашёл у ветку https://github.com/slytomcat/yandex-disk-indicator/issues/199
У меня стоит локаль en_GB.UTF-8, с ней раньше работало.
Что надо сделать чтобы заработало? (какие переменные окружения надо установить) Какую информацию надо предоставить для вас, чтобы решить проблему?

$ yandex-disk status
Synchronization core status: idle
Path to Yandex.Disk directory: '/home/alexander/ahome/ydisk'
	Total: 55 GB
	Used: 15.17 GB
	Available: 39.83 GB
	Max file size: 50 GB
	Trash size: 50.58 MB

Last synchronized items:
	file: 'screenshots/2018-10-30_16-33-24.png'
	file: 'screenshots/2018-10-30_16-33-16.png'

**Comment by slytomcat** [comment]
Локаль en_US.UTF8 на компе есть?

**Comment by slytomcat** [comment]
Если нет то обновите из dev, там убрана необходимость в этой локали.
```
wget https://raw.githubusercontent.com/slytomcat/yandex-disk-indicator/dev/yandex-disk-indicator.py -O /usr/bin/yandex-disk-indicator
chmod a+x /usr/bin/yandex-disk-indicator
```

**Comment by Alexander3XL** [comment]
Круто! Спасибо! И так быстро!
Добавил себе локаль en_US.UTF8 и всё заработало.
Мысль как найти разработчиков Яндекс.Диска
https://habr.com/company/yandex/blog/186752/
https://habr.com/company/yandex/blog/141458/
https://habr.com/company/yandex/workers/all/rating/
Там их много, осталось найти нужного)

**Comment by slytomcat** [comment]
Вы уже не первый кто без локали en_US.UTF8 наткнулся на эту проблему (еще один репорт был на форуме ubuntu.ru).
В мастере уже тоже выпилена необходимость в этой локали. 
Видимо надо выпустить релиз с этим фиксом.

**Comment by slytomcat** [comment]
Выпустил релиз https://github.com/slytomcat/yandex-disk-indicator/releases/tag/1.10.6 где убрана необходимость в наличии локали en_US.UTF8.

**Comment by Alexander3XL** [comment]
Пометил пакет в репозитории (ArchLinux) как устаревший и дал ссылки, скоро он появится в репозитории для всех)
Спасибо!
