### ISSUE TITLE
Push for inclusion in Russian Fedora

### ISSUE THREAD

**Issue by zsoltsandor** [slytomcat/yandex-disk-indicator#206]
I am switching to Fedora from KDE neon, and I would like to use Yandex.Disk with the indicator, but the latter is not part of any repository. It would be great to have it in the RFRemix repos, I'm sure it could fit in nicely.

**Comment by slytomcat** [comment]
Indicator has DEB/Launchpad PPA repo managed by me and RPM repos  (https://pkgs.org/download/yandex-disk-indicator) for ROSA and ALT that managed by other people.

I have no understanding and no platform to build/test a package for RFRemix repos. 

Any one who have such knowledge/platform for tests are welcome to build package.
I can provide any support for that person.

PS you also can install indicator from source. It is Python3/bash code that not require a real binary builds.

**Comment by surfernsk** [comment]
@slytomcat Готово. [fedora](http://copr.fedorainfracloud.org/coprs/surfernsk/Personal_repos/)
@zsoltsandor try:
```
sudo dnf copr enable surfernsk/Personal_repos
sudo dnf install yandex-disk-indicator

**Comment by slytomcat** [comment]
@surfernsk, Оу! Спасибо за столь быструю реакцию!
По возможности подключите нотификации о выпуске новых релизов. Или даже автоматическую пере-сборку. Я в последнее время не часто релизы выпускаю, поэтому стоит как-то автоматизировать отслеживание - релизы обычно с фиксами всяких новых траблов вылезающих из за обновлений в связанных пакетах/утилитах.

**Comment by surfernsk** [comment]
@slytomcat Ок, буду отслеживать.

**Comment by zsoltsandor** [comment]
@surfernsk thanks, I will be using this copr repo.
