### ISSUE TITLE
No fm-actions for caja

### ISSUE THREAD

**Issue by azlk** [slytomcat/yandex-disk-indicator#212]
Извините, но я не нашел расширений для файлового менеджера caja, т.е. после установки в меню caja ничего не появилось, касаемо yandex disk. Посмотрел в коде, но там, по-моему, только Dolphin, Nautilus_Nemo и pantheon-files...

Describe your OS (distribution, version, desktop environment)
Linux Mint 18.3 Mate

**Comment by slytomcat** [comment]
Если вы знаете как добавляются файловые расширения для caja, то вы можете оформить pull request в ветку dev с приблизительной реализацией (в функции activateActions в tools.py) по образу и подобию остальных, и я помогу отладить и добавлю это в master ветку.

**Comment by slytomcat** [comment]
Кроме того, судя по вот этому https://unix.stackexchange.com/questions/430705/add-custom-menu-action-to-caja-file-manager там придется еще доставлять какие-то дополнения, так что нужно еще и FAQ|Wiki какое-то описание добавлять - как это все настроить в caja...

**Comment by azlk** [comment]
> Если вы знаете как добавляются файловые расширения для caja, то вы можете оформить pull request в ветку dev с приблизительной реализацией (в функции activateActions в tools.py) по образу и подобию остальных, и я помогу отладить и добавлю это в master ветку.

Увы, питон я не знаю...ну да ладно, спасибо, что объяснили

**Comment by azlk** [comment]
> Если вы знаете как добавляются файловые расширения для caja, то вы можете оформить pull request в ветку dev с приблизительной реализацией (в функции activateActions в tools.py) по образу и подобию остальных, и я помогу отладить и добавлю это в master ветку.

Увы, питон я не знаю...ну да ладно, спасибо, что объяснили

**Comment by azlk** [comment]
> Если вы знаете как добавляются файловые расширения для caja, то вы можете оформить pull request в ветку dev с приблизительной реализацией (в функции activateActions в tools.py) по образу и подобию остальных, и я помогу отладить и добавлю это в master ветку.

Увы, питон я не знаю...ну да ладно, спасибо, что объяснили

**Comment by slytomcat** [comment]
Ну питон там только обрамление, сами команды там типа команд в баше или в XML,
Эти команды призваны добавить в систему расширений конкретного файлового менеджера две команды:

Команда которую нужно вызвать для добавления ссылки в буфер обмена (предоставление общего доступа) : yandex-disk publish <путь и имя файла в каталоге YandexDisk> 

Команда на удаление из общего доступа: yandex-disk unpublish <путь и имя файла в каталоге YandexDisk>
