### ISSUE TITLE
Namespace Notify not available for version 0.9

### ISSUE THREAD

**Issue by 13werwolf13** [slytomcat/yandex-disk-indicator#213]
Traceback (most recent call last):
  File "/usr/bin/yandex-disk-indicator", line 31, in <module>
    require_version('Notify', '0.9')
  File "/usr/lib64/python3.7/site-packages/gi/__init__.py", line 133, in require_version
    (namespace, version))
ValueError: Namespace Notify not available for version 0.9

OpenSuSe Tumbleweed
https://build.opensuse.org/package/show/home%3ADead_Mozay/yandex-disk-indicator

**Comment by 13werwolf13** [comment]
Насколько я понимаю пришло время обновить Notify с 0.7 до 0.9

**Comment by slytomcat** [comment]
ValueError: Namespace Notify not available for version 0.9 - так нету 0.9 версии вот и ругается - с 0.7 (как в оригинальном коде) - все работает.

О чем ошибка то - не понимаю?

**Comment by 13werwolf13** [comment]
не ошибка, указал на то что во многих дистрибутивах уже не опакечивают устаревшую версию

**Comment by slytomcat** [comment]
Можно конкретнее - в каких дистрибутивах Notify v.0.7 не поддерживается?

В ubuntu 18.04 наоборот ругается на v.0.9 (как у вас в примере). Т.о. одну версию для всех дистрибутивов не указать в принципе.

**Comment by 13werwolf13** [comment]
OpenSuSe Leap 15.0
OpenSuSe Leap 15.1
OpenSuSe Tumbleweed
Arch
И большинство дистрибутивов распространяющихся по модели Rolling release

К сожалению я не достаточно компетентен и не знаю насколько версии между собой обратносовместимы.

**Comment by slytomcat** [comment]
Теоретически можно просто убрать строчку 10 "require_version('Notify', '0.7')" и будет грузится версия которая найдется. Но при запуске индикатора будет ругаться:

```
  indicator.py:11: PyGIWarning: Notify was imported without specifying a version first. Use 
  gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
    from gi.repository import Notify
```

**Comment by 13werwolf13** [comment]
Да, так работает. но похоже больше на костыль чем на решение. Тем не менее спасибо.

**Comment by slytomcat** [comment]
Ну пока некостыльного решения не вижу.
Тут пока вообще не много вижу вариантов:
1. Правим код под "новые дистрибутивы" при сборке пакетов для них, позже можно будет перейти к правке кодов только "старых дистрибутивов" - мартышкин труд.
2. Убираем контроль версий (и получаем варнинги) - кривой костыль.
3. пишем код который в зависимости от дистрибутива пытается выбирать нужную версию - это просто велосипед из костылей, ИМХО.

**Comment by 13werwolf13** [comment]
Выбирать версию либы по дистрибутиву костыль безспорный, а как насчёт выбор версии либы по наличию самой либы?

**Comment by slytomcat** [comment]
... а как наличие то проверять... (я не знаю)

**Comment by 13werwolf13** [comment]
```
import PACKAGE
print(PACKAGE.__version__)
```
емнип как-то так

**Comment by slytomcat** [comment]
На импорт уже та ругань что я показывал выше.

**Comment by slytomcat** [comment]
вот тут https://pygobject.readthedocs.io/en/latest/guide/api/api.html нарыл gi.check_version(<package>, <version>)

Но она раизит ValueError если подходящей либы/версии нет.

С обработкой ексепшена импорт поучается просто монструозный.

А главное версии то надо знать что бы их проверять....

костыли - наше все....

**Comment by slytomcat** [comment]
В общем пока не вижу нормального решения.
