### ISSUE TITLE
Open Yandex.Disk folder when left click on tray icon

### ISSUE THREAD

**Issue by ivangretsky** [slytomcat/yandex-disk-indicator#215]
Good day! 
Thanks for a wonderful tool! Благодарю за отличную и нужную программу!

I am using it on Linux Mint. When I left click on the icon in the taskbar, a pop up menu opens. This is the same behaviour as when I right click on it. The default behaviour on Windows is to open Yandex.Disk folder in the file browser. I think this would be awesome either by default or at least as a configurable option. This action is listed in the pop up menu and works as intended, so shoul not be hard to implement.

What do you think?

**Comment by slytomcat** [comment]
Left and right clicks are controlled by panel plugin for application icons. There is no so much control from AppIndicator side on the way how menu is opened.
But let me check it. May be my current undestanding of it is not fully correct.

**Comment by slytomcat** [comment]
I checked the documentation for the GUI library I use. There is no way to control the left / right click in it.

So, unfortunately the requested change can be implemented.
