### ISSUE TITLE
Is it possible to limit (restrict) the upload (or download) synchro speed on debian PC?

### ISSUE THREAD

**Issue by nutrialex** [slytomcat/yandex-disk-indicator#217]
**My router's upload speed is maximum 1.2MByte/s. Yadex reaches this limit quickly and after 1 minute aproximetly my router reconnects. So I have to wait for yadex to reconnects and start again the synchronization after 2 minutes**
yd-tools (1.11.0)
yandex-disk_0.1.0.103
**It happens every time I upload or sync a file even with browser**

**MX Linux 18.3
Linux 4.19.0.1-amd64
Debian 9.4 (Stretch)
Xfce4**

**Comment by slytomcat** [comment]
Unfortunately I can't help you. My yd-tools(yandex-disk-indicator) app is only desktop icon to show the status of oficial Yandex.Disk utility (yandex-disk). All network activity is under control of yandex-disk.

Please addrss your problem to Yandex support team.
