### ISSUE TITLE
ModuleNotFoundError: No module named 'gi'

### ISSUE THREAD

**Issue by vasiliy0s** [slytomcat/yandex-disk-indicator#222]
Hello,

I cannot start the indicator because of the next issue:

```sh
(python3.9.0) ➜  ~ yandex-disk-indicator -l10

Traceback (most recent call last):
  File "/usr/bin/yandex-disk-indicator", line 26, in <module>
    from gi import require_version
ModuleNotFoundError: No module named 'gi'
```
System info:
```sh
(python3.9.0) ➜  ~ python --version
Python 3.9.0
(python3.9.0) ➜  ~ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal
(python3.9.0) ➜  ~ deactivate 
➜  ~ python --version
zsh: command not found: python
➜  ~ python3 --version
Python 3.9.0
➜  ~ which python3
/usr/local/bin/python3
➜  ~ gdm3 --version
GDM 3.36.3
➜  ~ sudo apt install  gnome-shell-extension-appindicator 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
gnome-shell-extension-appindicator is already the newest version (33.1-0ubuntu0.20.04.2).
gnome-shell-extension-appindicator set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

_* Python was built from the sources because I need this specific version._

My OS is x64, btw)

**Comment by slytomcat** [comment]
Try to install python3-gi package manually:
`sudo apt-get install python3-gi `

**Comment by vasiliy0s** [comment]
> sudo apt-get install python3-gi

I was tried it as the first step after some googling:

```sh
➜  ~ sudo apt-get install python3-gi
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-gi is already the newest version (3.36.0-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

**Comment by vasiliy0s** [comment]
But I'm not sure it can help me, because my Python 3.9.0 was build from sources.

**Comment by slytomcat** [comment]
Probably you have to build python3-gi from sources for python 3.9.0 or just copy (dirty hack) it from 3.36.0 (from /usr/lib/python3/dist-packages/gi) to your 3.9.0 python library path.

**Comment by vasiliy0s** [comment]
Ok, got it. I'll back when I'll try it tomorrow. Thanks

**Comment by slytomcat** [comment]
... one more variant: just run indicator in Python 3.36.0 (if it still available in your OS).

**Comment by vasiliy0s** [comment]
Hi @slytomcat,

Here is the [trick](https://stackoverflow.com/a/37648798/2166908) helped me:

```sh
pip install pygobject
```

(`pip` in my setup is from virtualenv from the _Python3.9.0_ build)

**Comment by vasiliy0s** [comment]
Also, I rebuilt Python previously with enabled _sqlite_ `./configure --enable-loadable-sqlite-extensions --enable-optimizations`.

**Comment by vasiliy0s** [comment]
So, this issue can be closed now since the indicator is working fine now

**Comment by slytomcat** [comment]
Ok, it seems that `pip install pygobject` is the solution for necessary python environment for indicator when Python was build from sources. 

Probably it worth to add it to FAQ.
