### ISSUE TITLE
Не запускается синхронизация

### ISSUE THREAD

**Issue by Avenezer** [slytomcat/yandex-disk-indicator#224]
Добрый день. Благодарю Вас за прекрасный софт.

Недавно на одной машине столкнулся с проблемой - Индикатор работает, но синхронизация не запускается. После старта Индикатора (настроено на автозапуск синхронизации, но этого не происходит) в меню выбираю "Запустить сервис Яндекс диск". В процессах появляется
yandex-disk
и через 10 секунд процесс завершается.
Это можно повторять бесконечно с тем же результатом.

Индикатор и яндекс.диск переустанавливал, устройство на сайте инициализировал.

Информация о системе:
========================================================
[code]
System:    Kernel: 5.4.0-81-generic x86_64 bits: 64 compiler: gcc v: 9.3.0 Desktop: Cinnamon 4.6.7 
           wm: muffin dm: LightDM Distro: Linux Mint 20 Ulyana base: Ubuntu 20.04 focal 
Machine:   Type: Desktop Mobo: Micro-Star model: MEG X570 UNIFY (MS-7C35) v: 2.0 serial: <filter> 
           UEFI: American Megatrends LLC. v: A.90 date: 05/17/2021 
CPU:       Topology: 12-Core model: AMD Ryzen 9 5900X bits: 64 type: MT MCP arch: Zen 3 
           L2 cache: 6144 KiB 
           flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm bogomips: 177598 
           Speed: 3800 MHz min/max: 2200/3700 MHz Core speeds (MHz): 1: 3806 2: 3797 3: 2235 
           4: 2562 5: 3807 6: 3813 7: 4757 8: 3817 9: 3803 10: 3804 11: 2332 12: 2336 13: 4752 
           14: 2236 15: 2232 16: 2217 17: 2509 18: 3810 19: 3812 20: 3810 21: 2242 22: 2343 
           23: 2210 24: 2232 
Graphics:  Device-1: AMD Navi 10 [Radeon RX 5600 OEM/5600 XT / 5700/5700 XT] 
           vendor: Micro-Star MSI driver: amdgpu v: kernel bus ID: 2f:00.0 chip ID: 1002:731f 
           Display: x11 server: X.Org 1.20.11 driver: amdgpu,ati 
           unloaded: fbdev,modesetting,radeon,vesa resolution: 2560x1080~60Hz, 2560x1080~60Hz 
           OpenGL: 
           renderer: AMD Radeon RX 5700 XT (NAVI10 DRM 3.35.0 5.4.0-81-generic LLVM 12.0.0) 
           v: 4.6 Mesa 21.0.3 direct render: Yes 
Audio:     Device-1: AMD Navi 10 HDMI Audio driver: snd_hda_intel v: kernel bus ID: 2f:00.1 
           chip ID: 1002:ab38 
           Device-2: AMD Starship/Matisse HD Audio vendor: Micro-Star MSI driver: snd_hda_intel 
           v: kernel bus ID: 31:00.4 chip ID: 1022:1487 
           Sound Server: ALSA v: k5.4.0-81-generic 
Network:   Device-1: Realtek RTL8125 2.5GbE vendor: Micro-Star MSI driver: r8169 v: kernel 
           port: f000 bus ID: 27:00.0 chip ID: 10ec:8125 
           IF: enp39s0 state: up speed: 1000 Mbps duplex: full mac: <filter> 
           Device-2: Intel Wi-Fi 6 AX200 driver: iwlwifi v: kernel port: f000 bus ID: 28:00.0 
           chip ID: 8086:2723 
           IF: wlo1 state: up mac: <filter> 
Drives:    Local Storage: total: 17.74 TiB used: 11.81 TiB (66.6%) 
           ID-1: /dev/nvme0n1 vendor: Samsung model: SSD 970 EVO Plus 500GB size: 465.76 GiB 
           speed: 31.6 Gb/s lanes: 4 serial: <filter> 
           ID-2: /dev/nvme1n1 vendor: Samsung model: SSD 970 EVO Plus 500GB size: 465.76 GiB 
           speed: 31.6 Gb/s lanes: 4 serial: <filter> 
           ID-3: /dev/sda vendor: Western Digital model: WUH721414ALE6L4 size: 12.73 TiB 
           speed: 6.0 Gb/s serial: <filter> 
           ID-4: /dev/sdb vendor: Samsung model: SSD 860 EVO 1TB size: 931.51 GiB speed: 6.0 Gb/s 
           serial: <filter> 
           ID-5: /dev/sdc vendor: Western Digital model: WD4002FYYZ-01B7CB0 size: 3.64 TiB 
           speed: 6.0 Gb/s serial: <filter> 
Partition: ID-1: / size: 143.05 GiB used: 63.79 GiB (44.6%) fs: btrfs dev: /dev/nvme0n1p2 
           ID-2: /home size: 257.49 GiB used: 129.71 GiB (50.4%) fs: btrfs dev: /dev/nvme0n1p5 
           ID-3: swap-1 size: 465.76 GiB used: 80.5 MiB (0.0%) fs: swap dev: /dev/nvme1n1 
USB:       Hub: 1-0:1 info: Full speed (or root) Hub ports: 6 rev: 2.0 chip ID: 1d6b:0002 
           Device-1: 1-1:2 info: USB OPTICAL MOUSE type: Mouse driver: hid-generic,usbhid rev: 1.1 
           chip ID: 275d:0ba6 
           Device-2: 1-4:3 info: Intel type: Bluetooth driver: btusb rev: 2.0 chip ID: 8087:0029 
           Hub: 1-5:7 info: Microchip (formerly SMSC) USB2734 ports: 5 rev: 2.1 chip ID: 0424:2734 
           Device-3: 1-5.5:9 info: Microchip USB2734 type: HID driver: hid-generic,usbhid rev: 2.0 
           chip ID: 04d8:0b27 
           Hub: 2-0:1 info: Full speed (or root) Hub ports: 4 rev: 3.1 chip ID: 1d6b:0003 
           Hub: 3-0:1 info: Full speed (or root) Hub ports: 6 rev: 2.0 chip ID: 1d6b:0002 
           Device-4: 3-5:2 info: Micro Star MYSTIC LIGHT type: HID driver: hid-generic,usbhid 
           rev: 1.1 chip ID: 1462:7c35 
           Hub: 3-6:3 info: Genesys Logic Hub ports: 4 rev: 2.0 chip ID: 05e3:0608 
           Device-5: 3-6.2:4 info: NZXT type: HID driver: hid-generic,usbhid rev: 2.0 
           chip ID: 1e71:2007 
           Hub: 4-0:1 info: Full speed (or root) Hub ports: 4 rev: 3.1 chip ID: 1d6b:0003 
           Hub: 5-0:1 info: Full speed (or root) Hub ports: 4 rev: 2.0 chip ID: 1d6b:0002 
           Device-6: 5-2:2 info: SiGma Micro Keyboard type: Keyboard,HID 
           driver: hid-generic,usbhid rev: 1.1 chip ID: 1c4f:0026 
           Hub: 6-0:1 info: Full speed (or root) Hub ports: 4 rev: 3.1 chip ID: 1d6b:0003 
Sensors:   System Temperatures: cpu: 36.0 C mobo: N/A gpu: amdgpu temp: 56 C 
           Fan Speeds (RPM): N/A gpu: amdgpu fan: 797 
Repos:     No active apt repos in: /etc/apt/sources.list 
           Active apt repos in: /etc/apt/sources.list.d/additional-repositories.list 
           1: deb https: //downloads.sourceforge.net/project/apacheoo-deb/debian testing main
           Active apt repos in: /etc/apt/sources.list.d/brave-browser-release.list 
           1: deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg arch=amd64] https: //brave-browser-apt-release.s3.brave.com/ stable main
           Active apt repos in: /etc/apt/sources.list.d/deadsnakes-ppa-focal.list 
           1: deb http: //ppa.launchpad.net/deadsnakes/ppa/ubuntu focal main
           Active apt repos in: /etc/apt/sources.list.d/google-chrome.list 
           1: deb [arch=amd64] http: //dl.google.com/linux/chrome/deb/ stable main
           Active apt repos in: /etc/apt/sources.list.d/home:stevenpusser.list 
           1: deb http: //download.opensuse.org/repositories/home:/stevenpusser/xUbuntu_20.04/ /
           Active apt repos in: /etc/apt/sources.list.d/inkscape_dev-stable-focal.list 
           1: deb http: //ppa.launchpad.net/inkscape.dev/stable/ubuntu focal main
           Active apt repos in: /etc/apt/sources.list.d/kdenlive-kdenlive-stable-focal.list 
           1: deb http: //ppa.launchpad.net/kdenlive/kdenlive-stable/ubuntu focal main
           Active apt repos in: /etc/apt/sources.list.d/linuxuprising-java-focal.list 
           1: deb http: //ppa.launchpad.net/linuxuprising/java/ubuntu focal main
           Active apt repos in: /etc/apt/sources.list.d/linuxuprising-shutter-focal.list 
           1: deb http: //ppa.launchpad.net/linuxuprising/shutter/ubuntu focal main
           Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list 
           1: deb http: //packages.linuxmint.com ulyana main upstream import backport #id:linuxmint_main
           2: deb http: //archive.ubuntu.com/ubuntu focal main restricted universe multiverse
           3: deb http: //archive.ubuntu.com/ubuntu focal-updates main restricted universe multiverse
           4: deb http: //archive.ubuntu.com/ubuntu focal-backports main restricted universe multiverse
           5: deb http: //security.ubuntu.com/ubuntu/ focal-security main restricted universe multiverse
           6: deb http: //archive.canonical.com/ubuntu/ focal partner
           Active apt repos in: /etc/apt/sources.list.d/skype-stable.list 
           1: deb [arch=amd64] https: //repo.skype.com/deb stable main
           Active apt repos in: /etc/apt/sources.list.d/slytomcat-ppa-focal.list 
           1: deb http: //ppa.launchpad.net/slytomcat/ppa/ubuntu focal main
           Active apt repos in: /etc/apt/sources.list.d/teams.list 
           1: deb [arch=amd64] https: //packages.microsoft.com/repos/ms-teams stable main
           Active apt repos in: /etc/apt/sources.list.d/trueconf.list 
           1: deb [arch=amd64] http: //deb.trueconf.com/linuxmint/ ulyana non-free
           Active apt repos in: /etc/apt/sources.list.d/yandex-browser-beta.list 
           1: deb [arch=amd64] http: //repo.yandex.ru/yandex-browser/deb beta main
           Active apt repos in: /etc/apt/sources.list.d/yandex-disk.list 
           1: deb http: //repo.yandex.ru/yandex-disk/deb/ stable main
           Active apt repos in: /etc/apt/sources.list.d/zotero.list 
           1: deb https: //github.com/retorquere/zotero-deb/releases/download/apt-get/ ./
Info:      Processes: 686 Uptime: 9d 3h 34m Memory: 125.80 GiB used: 21.03 GiB (16.7%) 
           Init: systemd v: 245 runlevel: 5 Compilers: gcc: 9.3.0 alt: 9 
           Client: Unknown python3.8 client inxi: 3.0.38 
[/code]
========================================================

Выдача yandex-disk-indicator -l10:
=============
2021-10-16 13:54:29,218 INFO     yandex-disk-indicator v.1.11.0
2021-10-16 13:54:29,219 DEBUG    Logging level: 10
2021-10-16 13:54:29,219 DEBUG    Config value read as: autostart = True
2021-10-16 13:54:29,219 DEBUG    Config value read as: notifications = True
2021-10-16 13:54:29,219 DEBUG    Config value read as: theme = False
2021-10-16 13:54:29,219 DEBUG    Config value read as: fmextensions = True
2021-10-16 13:54:29,219 DEBUG    Config value read as: daemons = /home/sancho/.config/yandex-disk/config.cfg
2021-10-16 13:54:29,220 INFO     Config read: /home/sancho/.config/yd-tools/yandex-disk-indicator.conf
2021-10-16 13:54:29,236 DEBUG    Config value read as: auth = /home/sancho/.config/yandex-disk/passwd
2021-10-16 13:54:29,236 DEBUG    Config value read as: dir = /mnt/mmedia/Yandex.Disk
2021-10-16 13:54:29,236 DEBUG    Config value read as: proxy = False
2021-10-16 13:54:29,236 INFO     Config read: /home/sancho/.config/yandex-disk/config.cfg
2021-10-16 13:54:29,543 DEBUG    Event raised by Timer
2021-10-16 13:54:29,543 INFO     Change event: stat,size,
2021-10-16 13:54:29,544 DEBUG    Sub-menu 'Last synchronized' has 0 items
2021-10-16 13:54:29,544 INFO     Status: unknown -> none
2021-10-16 13:54:30,118 INFO     Daemon started, message: Запуск демона...Готово

2021-10-16 13:54:31,567 DEBUG    Event raised by Timer
2021-10-16 13:54:31,567 INFO     Change event: ,,last
2021-10-16 13:54:31,569 DEBUG    Sub-menu 'Last synchronized' has 10 items
2021-10-16 13:54:38,631 DEBUG    Event raised by Timer
2021-10-16 13:54:38,631 INFO     Change event: stat,size,
2021-10-16 13:54:43,659 DEBUG    Event raised by Timer
2021-10-16 13:54:43,659 INFO     Change event: stat,,
2021-10-16 13:54:49,691 DEBUG    Event raised by Timer
2021-10-16 13:54:49,691 INFO     Change event: stat,,
2021-10-16 13:54:56,714 DEBUG    Event raised by Timer
2021-10-16 13:54:56,714 INFO     Change event: stat,size,last
2021-10-16 13:54:56,715 DEBUG    Sub-menu 'Last synchronized' has 0 items
2021-10-16 13:55:39,660 DEBUG    Event raised by Watcher
2021-10-16 13:55:39,660 INFO     Change event: ,,last
2021-10-16 13:55:39,662 DEBUG    Sub-menu 'Last synchronized' has 10 items
2021-10-16 13:55:39,755 INFO     Daemon started, message: Запуск демона...Готово

2021-10-16 13:55:46,734 DEBUG    Event raised by Timer
2021-10-16 13:55:46,734 INFO     Change event: ,size,
2021-10-16 13:55:50,776 DEBUG    Event raised by Timer
2021-10-16 13:55:50,776 INFO     Change event: stat,,
2021-10-16 13:55:55,799 DEBUG    Event raised by Timer
2021-10-16 13:55:55,799 INFO     Change event: stat,,
2021-10-16 13:56:01,825 DEBUG    Event raised by Timer
2021-10-16 13:56:01,825 INFO     Change event: stat,,
2021-10-16 13:56:08,850 DEBUG    Event raised by Timer
2021-10-16 13:56:08,850 INFO     Change event: stat,size,last
2021-10-16 13:56:08,851 DEBUG    Sub-menu 'Last synchronized' has 0 items
2021-10-16 13:56:51,202 DEBUG    Event raised by Watcher
2021-10-16 13:56:51,202 INFO     Change event: ,,last
2021-10-16 13:56:51,203 DEBUG    Sub-menu 'Last synchronized' has 10 items
2021-10-16 13:56:51,395 INFO     Daemon started, message: Запуск демона...Готово

2021-10-16 13:56:58,278 DEBUG    Event raised by Timer
2021-10-16 13:56:58,279 INFO     Change event: ,size,
2021-10-16 13:57:02,318 DEBUG    Event raised by Timer
2021-10-16 13:57:02,318 INFO     Change event: stat,,
2021-10-16 13:57:07,350 DEBUG    Event raised by Timer
2021-10-16 13:57:07,350 INFO     Change event: stat,,
2021-10-16 13:57:13,378 DEBUG    Event raised by Timer
2021-10-16 13:57:13,378 INFO     Change event: stat,size,last
2021-10-16 13:57:13,380 DEBUG    Sub-menu 'Last synchronized' has 0 items
^C2021-10-16 13:57:23,079 DEBUG    Exit started
2021-10-16 13:57:23,079 DEBUG    Indicator exit started: 
2021-10-16 13:57:23,079 DEBUG    Indicator exited
=============

Прошу вашей помощи.

Алексей.
alex@harlamenkov.ru

**Comment by slytomcat** [comment]
На момент запуска  /mnt/mmedia/Yandex.Disk уже смонтировано? 
Демон яндекса часто дурит, когда устройство медленно монтируется. 

По логам видно что индикатор запускает yandex-disk успешно ('INFO Daemon started, message: Запуск демона...Готово'), Но дальше как-то все странно. Там похоже что-то происходит, но индикатор долго не ловит события по изменению лога синхронизации ('DEBUG Event raised by Timer'). Обычно, когда демон нормально стартует, то он в первую очередь начинает активно писать в свой лог синхронизации и индикатор отлавливает эти события ('Event raised by Watcher') получает обновления статуса.

А можете еще показать что пишется в /mnt/mmedia/Yandex.Disk/.sync/cli.log и может там еще какие-то крашлоги есть - их бы посмотреть - может в них есть конкретика почему демон вываливается через 10 секунд.

Тут проблема явно в работе демона. И, возможно, вам лучше (но вряд ли быстрее) смогут помочь в поддержке Яндексе.

**Comment by Dmitriy-Kulagin** [comment]
Возможно вы сможете лучше понять что происходит если запустите yandex-disk из терминала - возможно он там сообщит почему падает.

Кстати, вот еще какой вижу вероятный вариант: демон стартовал когда /mnt/mmedia/Yandex.Disk еще не был смонтирован и просто попытался в каталоге для монирования создать нужные структуры, а после этого том смонтировался и демон обнаружил там "старые" файлы и тупо крашнулся (не переварив такого издевательства над собой). Ну а далее в любом следующем запуске он находит что-то такое что он успел в процессе первого краша записать, и прочитав это опять крашится. 

Я бы попробовал сделать две вещи: 1. отмонтировать /mnt/mmedia/Yandex.Disk после чего вытереть все (если оно там есть) из каталога в который монтируется том. 2. смонтировать том и стереть все из /mnt/mmedia/Yandex.Disk/.sync (хотя лучше сделать резервную копию .sync перед этим). 
И вот только после этого пытаться запускать демона.

Но это только предположение - не относитесь к моему рецепту как однозначно правильному и корректному (потому и советую сделать бекапы перед тем как пробовать).

**Comment by slytomcat** [comment]
Что-то нет никакой информации
