### ISSUE TITLE
Не запускается индикатор

### ISSUE THREAD

**Issue by Stalker-medik** [slytomcat/yandex-disk-indicator#228]
После обновления не запускается индикатор. При запуске в терминале ругается на строку 31.

Traceback (most recent call last):
  File "/bin/yandex-disk-indicator", line 31, in <module>
    require_version('Notify', '0.7')
  File "/usr/lib/python3.10/site-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available for version %s' %
ValueError: Namespace Notify not available for version 0.7

При замене версии Notify c 0.7 на 0.8 (установленную в системе) запускается без ошибок.

**Comment by slytomcat** [comment]
Что за дистрибутив и какая версия дистрибутива?

**Comment by Stalker-medik** [comment]
Arch linux x86_64, обновления последние на 16.07.2022 года, libnotify 0.8.0-2.
P.S. Проблема не только с Вашей программой, а ещё с некоторыми https://gitlab.gnome.org/GNOME/libnotify/-/issues/27
Всё именно из-за обновления версии libnotify c 0.7 на 0.8.
P.P.S. Разработчик libnotify поправил проблему с версией API модуля. Всё работает. Сорри, что зря потревожил. Проблему закрываю.

**Comment by slytomcat** [comment]
Ну на новую версию рано или поздно видимо все-таки стоит перевести. 
Посмотрю, что там лучше сделать. Возможно стоит поискать вариант выбора текущей версии или latest. 
Собственно когда-то давно там вообще было без указания версии, но поnом начались варнинги на то, что версии gi модулей явно не указаны. А явное указание версии как раз вот в таких кейсах в ногу стреляет. 
Причем, по идее, смена версии может сломать работу с библиотекой (из за изменения интерфейсов), но по факту почти все стараются совместимость версий обеспечить.
