### ISSUE TITLE
Indicator doesn't start

### ISSUE THREAD

**Issue by AuthorProxy** [slytomcat/yandex-disk-indicator#229]
1. Open CLI
2. yandex-disk-indicator <Enter>

```
Traceback (most recent call last):
  File "/usr/bin/yandex-disk-indicator", line 26, in <module>
    from gi import require_version
ModuleNotFoundError: No module named 'gi'
```

Installed latest from ppa, ubuntu 22

**Comment by slytomcat** [comment]
I have no idea why gi module is not available in ubuntu 22 (probably you mean 22.04?).

You may try to use another indicator https://github.com/slytomcat/yd-go - it is written in Golang and it require nothing additional libraries.

**Comment by slytomcat** [comment]
Probably the reason of the issue described in this [PR](https://github.com/slytomcat/yandex-disk-indicator/pull/230). The PR also contain fix for it.
Just install Indicator from source. PR with fix already applied to master and later I'll publish it via PPA.

**Comment by slytomcat** [comment]
I've updated PPA. If it is still issue with new version just inform me - I'll reopen it.
