### ISSUE TITLE
Выгрузка файлов

### ISSUE THREAD

**Issue by xthr0** [slytomcat/yandex-disk-indicator#231]
Как сделать так, чтобы при синхронизации файлы только выгружались с пк на диск, но не скачивались с диска на пк

**Comment by slytomcat** [comment]
За все манипуляции с файлами и облачным хранилищем отвечает утилита яндекса yandex-disk, индикатор отвечает только за вывод текущего статуса в панель уведомлений.

Что может и что не может yandex-disk можно узнать из его хелпа и на странице поддержки на сайте яндекса.
Если я не ошибаюсь, что-то похоже на то что вы хотите, делает опция read-only.
