### ISSUE TITLE
Ability to choose folder to exclude folders not from local storage but from Yandex.Disk

### ISSUE THREAD

**Issue by avmaksimov** [slytomcat/yandex-disk-indicator#234]
All Ok but better if it would be possible to choose not synchronized folder to exclude.

**Comment by slytomcat** [comment]
The all synchronization staff is performed by yandex-disk utility from Yandex company. Indicator is only responsible for showing synchronisation status in taskbar. 
So you can send this feature request to Yandex.

**Comment by avmaksimov** [comment]
Of course it's not a feature for indicator but at least you can add ability to add path structure manually - not choosing in file system (because excluding folder may not exist on disk - only online).
Maximum - I see. You don't want to add authtorization to the app and it's impossible to use passwd file from yandex-disk config.

**Comment by slytomcat** [comment]
You can add anything in excluded folders by editing ~/.config/yandex-disk/config.cfg in any text editor.

Yandex doesn't described the authentication process that they use for yandex-disk utility in any document available for public access. The authentication to yandex.disk which is described in oficial docs is absolutely incompatible with yandex-disk utility. So, there is no oficial way to use password file by other applications.

**Comment by avmaksimov** [comment]
Thank you for the explanation.
I know about config.cfg but if you don't want ability to manually adding folders as string (to add with subfolders) may be you'll consider the ability to open this file from your application?

**Comment by slytomcat** [comment]
I need to investigate such ability in open file dialog (it is standard dialog from GTK library).

But it is possible to create desired folder in the Yandex.Disk folder and add it through the open file dialog (to add it in excluded). Then it can be deleted. 

I understand that is rather annoying procedure but it have to be done only once.

**Comment by avmaksimov** [comment]
Thank you. I hope you'll find the way to make such dialog ).
