### ISSUE TITLE
Authorization by one-time password and qr code

### ISSUE THREAD

**Issue by jet1988** [slytomcat/yandex-disk-indicator#236]
add authorization by one-time password and qr code

**Comment by slytomcat** [comment]
Can you clarify what exactly you mean?
Authorization to what?

Indicator (this project) is the utility to show synchronization status on the desktop. All the rest (including authorization) is on side of yandex-disk utility from yandex company.

**Comment by slytomcat** [comment]
Closed due to no clarification provided.
