### ISSUE TITLE
Wrong title of the indicator in KDE tray

### ISSUE THREAD

**Issue by antonsoroko** [slytomcat/yandex-disk-indicator#238]
Describe what happened with indicator:
Кажется раньше было нормальное имя в трее, аля "Индикатор Яндекс.Диск", а теперь просто `indicator.py`. Ну или меня глючит, но тогда есть смысл сделать нормальное имя :-)

Describe steps to recreate the issue:
обновиться до 1.12.0 при KDE 5
![image](https://github.com/slytomcat/yandex-disk-indicator/assets/17964763/8a47418f-63b7-4fd5-9ce8-fae90d9afbc4)

Describe your OS (distribution, version, desktop environment):

Операционная система: Kubuntu 23.04
Версия KDE Plasma: 5.27.4
Версия KDE Frameworks: 5.104.0
Версия Qt: 5.15.8
Версия ядра: 6.2.0-25-generic (64-бита)
Графическая платформа: X11

**Comment by slytomcat** [comment]
Скорее всего что то не так передается в создание индикатора, хотя там толком ничего не менялось...
Попробую разобраться....

**Comment by slytomcat** [comment]
Поправил в бранче dev. Можете из dev поставить как из исходников? 
Или просто скопируйте из dev файлы `indicator.py` и `daemon.py` в каталог `/usr/share/yd-tools/` своего компьютера (потребуется sudo).

**Comment by antonsoroko** [comment]
@slytomcat всё отлично, спасибо!

![image](https://github.com/slytomcat/yandex-disk-indicator/assets/17964763/cd812a25-3ed8-4c56-b0a6-b943e1aba81b)

**Comment by slytomcat** [comment]
Ок. Тогда соберу и опубликую на лаунчпад v1.12.1.
