### ISSUE TITLE
can't add ppa:slytomcat/ppa repository

### ISSUE THREAD

**Issue by trawglodyte** [slytomcat/yandex-disk-indicator#241]
Debian 12 - error after `sudo add-apt-repository ppa:slytomcat/ppa`, but I continued to show it won't install. Here is the full dialogue. 

[yd-tools install fail.txt](https://github.com/slytomcat/yandex-disk-indicator/files/12752989/yd-tools.install.fail.txt)

**Comment by slytomcat** [comment]
I have no idea why `/usr/bin/add-apt-repository` failing after `sudo add-apt-repository ppa:slytomcat/ppa`.
But if it fails the repository is not added and there is no way to install `yd-tools`.
I think it better to try found solution on debian resources.

**Comment by slytomcat** [comment]
May be this can help: https://www.linuxquestions.org/questions/debian-26/debian-bullseye-sid-add-apt-repository-not-working-python-problem-4175720821/

**Comment by trawglodyte** [comment]
I added python3-launchpadlib in synaptic. Now I can add ppa:slytomcat/ppa repository. 

Then when I `sudo apt update` I get error "404 Not Found [IP: 185.125.190.52 443]" and warnings about not having a Release file.

Well, I try to solve this by editing /etc/apt/sources.list.d/slytomcat-ubuntu-ppa-bookworm.list with [trusted=yes] after deb.

deb **[trusted=yes]** https://ppa.launchpadcontent.net/slytomcat/ppa/ubuntu/ bookworm main

But I just get the error in a different place when I `sudo apt update` again.

This shows results of `sudo apt update` before and after editing /etc/apt/sources.list.d/slytomcat-ubuntu-ppa-bookworm.list 

[404 Not Found error.txt](https://github.com/slytomcat/yandex-disk-indicator/files/12753969/404.Not.Found.error.txt)

**Comment by antonsoroko** [comment]
Looks like there are no `yd-tools` [builds](https://ppa.launchpadcontent.net/slytomcat/ppa/ubuntu/dists/) for [Debian Bookworm (12)](https://www.debian.org/releases/bookworm/) yet.

**Comment by trawglodyte** [comment]
> Looks like there are no `yd-tools` [builds](https://ppa.launchpadcontent.net/slytomcat/ppa/ubuntu/dists/) for [Debian Bookworm (12)](https://www.debian.org/releases/bookworm/) yet.

I installed on Debian 12 with the other method, downloading the tar.gz https://github.com/slytomcat/yandex-disk-indicator/releases/tag/1.11.0

The key was to install every dependency, including gir1.2-appindicator3-0.1 which wasn't in my repositories. I had gir1.2-ayatanaappindicator3-0.1, but needed gir1.2-appindicator3-0.1 as well to install and work.

It really is a marvelous little GUI (thanks to slytomcat). I dual-boot Ubuntu and Debian, it's so handy to auto-sync my files and backup to the cloud.

**Comment by slytomcat** [comment]
`yd-tools` is being built only for Ubuntu distributions on launchpad. Installing it on Debian distros - is always a little tricky task.
