### ISSUE TITLE
gir1.2-appindicator3-0.1 | gir1.2-ayatanaappindicator3-0.1

### ISSUE THREAD

**Issue by trawglodyte** [slytomcat/yandex-disk-indicator#242]
I saw this in dependencies and thought it meant either gir1.2-appindicator3-0.1 OR gir1.2-ayatanaappindicator3-0.1, well gir1.2-appindicator3-0.1 was not available in my synaptic package manager, but I had gir1.2-ayatanaappindicator3-0.1 so I didn't worry about it. I had or installed all other package dependencies.

yandex-disk-indicator did not install correctly and work by running install.sh until I downloaded gir1.2-appindicator3-0.1 from https://packages.debian.org/buster/gir1.2-appindicator3-0.1

It is working wonderfully now! Thanks so much slytomcat!

**Comment by slytomcat** [comment]
Can you clarify what exactly the issue about?

install.sh is only installing source code that works only when the all requirements had been installed before.

DEB package has dependencies inside and it try to install yet not installed requirements when it is installed.

**Comment by slytomcat** [comment]
Closed as no reaction from the issue creator for soo log time.
