### ISSUE TITLE
Ошибка работы настроек сервиса Яндекс Диск

### ISSUE THREAD

**Issue by AlexanderShad** [slytomcat/yandex-disk-indicator#245]
Добрый день.

Стенд:
OS: ALT Regular Sisyphus x86_64
Kernel: 6.6.18-un-def-alt1
DE: GNOME 45.4 
CPU: AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx (8) @ 2.100GHz
GPU: AMD ATI Radeon Vega Series / Radeon Vega Mobile Series

yandex-disk-indicator-1.12.2-alt1.noarch

Настройки индикатора
+ Запускать индикатор Яндекс.Диск при запуске компьютера
+ Показывать информационные сообщения
- Выбрать светлую тему иконок
+ Активировать расширения для файл-менеджера

Настройки сервиса Яндекс.Диск
Все выключено, checkbox.checked = disable

Ожидаемое поведение:
Запуск Яндекс.Диск индикатора при запуске системы. Не запускать синхранизацию Яндекс.Диска

Фактическое поведение:
Запуск Яндекс.Диск индикатора. Запуск синхранизации Яндекс.Диска

Предположение - ошибка:
Не работает отключение галочки Запускать сервис Яндекс.Диск при запуске индикатора.

**Comment by slytomcat** [comment]
Кроме индикатора yandex-disk может запускаться и через автоматический запуск приложений на старте системы. Ну, то есть, сам индикатор и прописывает в автостарт системы диск, когда выбирается настройка запуска диска при запуске индикатора. И он свою эту настройку убирает, когда снимается галочка в настройке. Но, если есть еще одна настройка - то ее индикатор не отключит.

Я бы посоветовал при отключенном запуске диска при старте индикатора посмотреть все (их несколько) механизмы авто-запуска приложений на старте системы (при инициализации профиля пользователя).

**Comment by AlexanderShad** [comment]
Здравствуйте.
Вы правы, в ~/.config/autostart был еще файл автозапуска Яндекс Диска.
Вопрос снят.
Спасибо
