### ISSUE TITLE
Синхронизация файлов после перезагрузки системы

### ISSUE THREAD

**Issue by mcdemon05** [slytomcat/yandex-disk-indicator#250]
Добрый день.
Иногда после перезагрузки системы, программа зачем-то сверяет все файлы.
Это невозможно незаметить т.к. кушает процессор и соответственно жужат кулеры, до тех пор пока проверка всех файлов не закончитс. Выглядит это как синхронизация, но сеть при этом используется не сильно поэтому делаю вывод, что сравниваются хэш суммы всех файлов.

По какой причине такое происходит?

Fedora 40, Gnome 46

**Comment by slytomcat** [comment]
Программа - какая именно?
Подозреваю что эта программа называется yandex-disk.
Индикатор (к проекту которого вы завели ишью) проверяет статус одного единственного файла в каталоге синхронизации yandex-disk-а. И индикатор вообще не занимается синхронизацией или каким-либо сканированием каталога. Он только показывает статус работы утилиты yandex-disk.
