### ISSUE TITLE
Кнопка в окне копирования ссылки не отображается корректно

### ISSUE THREAD

**Issue by a-e-egorov** [slytomcat/yandex-disk-indicator#251]
ОС: Linux Ubuntu 20.04 (GNOME 3.36.8, X11).
Кнопка "Копировать и закрыть" отображается пустой - см. приложенные снимки экрана.
![Снимок экрана от 2024-08-14 22-41-02](https://github.com/user-attachments/assets/0f926701-62ed-413e-bc52-ce02e3c2ac04)
![20240814_224045](https://github.com/user-attachments/assets/4e4eb623-1cfc-4ae7-9de0-0c9445587f4b)

**Comment by slytomcat** [comment]
А какой файловый менеджер?

Собственно расширения файловых менеджеров делались разными людьми и я не уверен что смогу тут помочь. Однако постараюсь посмотреть что именно там и как работает с вашим ФМ.

**Comment by slytomcat** [comment]
ну и еще покажите что в терминале выведет команда 
`echo $LANG | cut -c 1-2`

**Comment by a-e-egorov** [comment]
Да, файловый менеджер - Nautilus.
~$ echo $LANG
ru_RU.UTF-8
~$ echo $LANG | cut -c 1-2
ru

**Comment by slytomcat** [comment]
А как устанавливали индикатор?
Что у вас лежит в /usr/share/yd-tools/translations ?

**Comment by slytomcat** [comment]
Там в принципе простой [bash скрипт](https://github.com/slytomcat/yandex-disk-indicator/blob/master/fm-actions/Nautilus_Nemo/publish)

Я попробовал его по шагам выполнить (только ссылку руками написал в переменную `f`) и у меня все нормально вывелось:
![image](https://github.com/user-attachments/assets/284a8d4b-afa3-4f17-abbc-bacc03b8a776)

**Comment by a-e-egorov** [comment]
Я уже забыл точно, как устанавливал (очень давно). А в папке "translations" лежат след. файлы: "ya-setup-be.lang  ya-setup-bg.lang  ya-setup-en.lang  ya-setup-ru.lang". В целом, для меня это проблемой не является. Я просто сообщил отчасти на случай, чтобы это исправить, если проблема есть глобально у всех. Но она вполне м.б. локальной у меня..

**Comment by slytomcat** [comment]
Ну файлы нужные есть понять бы почему не работает у вас.
А вы попробуйте по-шагово скрипт выполнить -  только ту строчку что yandex-disk вызывает - можно заменить на `f=link`.

**Comment by a-e-egorov** [comment]
Ладно, сейчас нету времени на это.
