### ISSUE TITLE
Status: error

### ISSUE THREAD

**Issue by CTOlet** [slytomcat/yandex-disk-indicator#3]
Почему-то значек в трее все время красный и при открытии меню написано Status:error. В чем может быть проблема? Главное все файлы синхронизированны 100%

**Comment by slytomcat** [comment]
Просто кликните по статусу и посмотрите детальную информацию по ошибке.
Как правило там либо битая ссылка не синхронизируется либо ошибки связанные с правами доступа на файлы в синхронизируемом каталоге.

**Comment by slytomcat** [comment]
It is not an indicator isssue.
