### ISSUE TITLE
расширения для файл-менеджера

### ISSUE THREAD

**Issue by Fahreeve** [slytomcat/yandex-disk-indicator#49]
какая функциональность у этих расширений?
Не вижу разницы между включением и выключением их

**Comment by Fahreeve** [comment]
по идее он должен добавлять в контекстное меню пункты publish и unpublish. Но вот у меня это не наблюдается. Каким образом он определяет какой файловый менеджер запущен?

**Comment by slytomcat** [comment]
Расширения делались разными людьми под Nautilus, Thunar, Nemo и Dolphin.
Под Dolphin вроде что-то поменялось для последних версий, но пока руки не дошли поправить.
Какой у вас файловый менеджер - я угадать не могу - не телепат, увы. Потому и не могу сказать почему у вас не работает.

Наличие файловых менеджеров в системе  определяется по ответу команды dpkg -s <имя ФМ>.

**Comment by slytomcat** [comment]
Если включить уровень отладки 10 (переменная loglevel в файле ~/.config/yd-tools/yandex-disk-indicator.conf), запустить индикатор из консоли и подергать флажек настройки файловых расширений, то в консоли будет видно какие ФМ удалось найти.

**Comment by Fahreeve** [comment]
2015-12-25 21:07:17,634 INFO     Nautilus installed: False
2015-12-25 21:07:17,683 INFO     Nemo installed: False
2015-12-25 21:07:17,728 INFO     Thunar installed: False
2015-12-25 21:07:17,779 INFO     Dolphin installed: False

**Comment by Fahreeve** [comment]
я пользователь elementary os freya, у меня файловый менеджер pantheon-files

**Comment by Fahreeve** [comment]
сейчас пытаюсь сам прикрутить поддержку своего файлового менеджера
Есть ли возможность запросить права суперпользователя?

**Comment by Fahreeve** [comment]
опрос отпал

**Comment by slytomcat** [comment]
Если у вас pantheon-files, то под него нет готовых расширений в индикаторе. 

Если приделаете сами - можете в проект pull request-ом их предложить в папку fm-actions - я потом доделаю установку через настройки, если поможете еще парой ответов и тестированием.

**Comment by Fahreeve** [comment]
как раз этим занимаюсь

**Comment by Fahreeve** [comment]
есть какая-то возможность заблокировать уведомления от yd-tools на время?

**Comment by slytomcat** [comment]
А что значит заблокировать уведомления? В настройках индикатора есть пункт "показывать информационные сообщения" - это про нотификейшены что выскакивают при смене статуса демона синхронизации.

**Comment by Fahreeve** [comment]
мне нужно делать копирование и удаление файла через gksudo. Соответственно пользователь может отказаться от ввода пароля, тогда нужного действия не происходит, но чекбокс все равно меняет свое состояние. Как его вернуть в прежнее состояние?

**Comment by slytomcat** [comment]
Нет, вам не нужно лезть в системные каталоги - все файловые менеджеры имеют настройки в пользовательком домашнем каталоге. Т.е. есть настройки и в системных каталогах но они переопределяются пользовательскими.

Обычно копии системных настроек в ~/.config/<имя программы> или в ~/.<имя программы>

А чекбокс - его как поставили так и сняли. 

Но я бы не советовал вам заниматься интергацией расширений - просто дайте мне нужные файлы и разберитесь куда их копировать в хомяке и я до делаю установку файлов в индикаторе сам.

**Comment by Fahreeve** [comment]
проблема в том, что pantheon-files не имеет каталога с копией настроек.

**Comment by slytomcat** [comment]
Как я понял после некторого гугления pantheon-files испольует для настроек gsettings.... 
Т.е. нужно делать настройки через gconf-tools, при этом настройки dconf тоже делятся на пользовательские и системные и для пользовательских sudo не нужно.

**Comment by Fahreeve** [comment]
для того чтобы добавить пункт в контекстное меню, надо добавить файлики в папку /usr/share/contractor, а это можно сделать только под рутом

**Comment by slytomcat** [comment]
Да, неприятная история :( 

Ну пусть будет так. 

Я попробую допилить передачу реакции из activateActions, что бы чекбокс не изменялся, если не удалось активировать или дезактивировать расширения. Тогда если пользователь пароль в gksu не введет то и чекбокс не изменится - будет наглядно понятно что ничего не получилось.

**Comment by slytomcat** [comment]
Слил все в dev ветке (вручную). 
Вам сделать .deb для тестирования?

**Comment by Fahreeve** [comment]
да, было бы неплохо, но исходник я уже протестировал

**Comment by slytomcat** [comment]
сейчас пришлю на почту - лучше протестировать все в целом.

**Comment by slytomcat** [comment]
Я же там еще возврат статуса в окно настроек сделал - надо бы проверить что чекбокс не меняется если не введен пароль для gksu

**Comment by Fahreeve** [comment]
нашел один недочет. К своему стыду не знаю как мне обновить мой форк(
Когда есть окошко для ввода пароля суперпользователя, есть кнопка отменить. Если на нее нажать, то снова появляется это же окно. Таким образом я не могу отменить действие

**Comment by slytomcat** [comment]
В ваш форк могу пулл реквест сделать с полным паетом изменений. 

По поводу отмены - так у вас там два раза вызывается - вот оно врой раз и спрашивает (как я понимаю).

**Comment by Fahreeve** [comment]
не-не у меня вызывается 1 раз и должно вызываться один раз. Но при нажатии на кнопку отмена, окно с просьбой ввести пароль появляется снова и снова

**Comment by slytomcat** [comment]
Странно.... а если неверный пароль ввести - та же ситуация? Закрыть окно можно?

**Comment by Fahreeve** [comment]
![2015-12-30 11 01 06](https://cloud.githubusercontent.com/assets/3227524/12047933/a6f953aa-aee4-11e5-8b18-72853219bffc.png)
вот сделал скриншот, в нормальном режиме нет этого прозрачного окна. Как видно тут всего 2 кнопки. Если нажать отмена то появится оно же, если ввести неправильный пароль, то появится опять это же окно и там дополнительно будет написано мол неправильный пароль

**Comment by Fahreeve** [comment]
и такое поведение появилось после того как была добавлена переменная result

**Comment by Fahreeve** [comment]
и есть еще один вопроса про автозагрузку в конфиге телеграма есть такие строчки:

```
StartupNotify=true
X-GNOME-Autostart-enabled=true
```

а в вашем конфиге только:

```
X-GNOME-Autostart-enabled=false
```

**Comment by slytomcat** [comment]
По поводу автозагрузки (.desktop файлы) - там в принципе можно что угодно писать - значение для автозапуска имеет только параметр Exec.

Просто у меня одни и те же файлы используются и для меню приложений и для автозапуска.
Просто эти файлы при установке и так ложатся в /usr/share/aplications, так я и решил их не хранить отдельно и беру их оттуда для копирования в ~/config/autostart

По поводу переменной result так она никак на ваш код не влияет. Она просто дополнительно прописана в вами написанный if... можно ради эксперимента убрать ее но я даже включая буйную фантазию не могу представить как добавление доп переменной в коде python могло повлиять на то, что выполняется в отдельном процессе ОС (в своем собственном окружении).

**Comment by Fahreeve** [comment]
можно ли как-то проверять и вот эту строчку  `X-GNOME-Autostart-enabled=false` для автозапуска? для elemntary os это было бы более нативным и удобным

**Comment by slytomcat** [comment]
Проверять X-GNOME-Autostart-enabled=fals/true - конечно же более правильно. Но, честно говоря, мне кажется, что управлять автостартом тогда надо из утилит ОС, а не из настроек индикатора. Для индикатора важно что его автостарт включен наличием файла в ~/.config/autostart, а если пользователь залез в утилиты ос и там запретил исполнение автозапуска - то как бы он сам должен понимать что он делает.

**Comment by Fahreeve** [comment]
ну в моем случае утилиты меняют именно эту строчку. Давайте тогда этот пункт в туду запишем, там определенно не все так просто

**Comment by Fahreeve** [comment]
и второй вопрос: почему отступ 2 пробела, а не 4?)

**Comment by slytomcat** [comment]
2 - потому что так код компактнее. Глубина вложенностей в коде порой довольно большая и даже с длинной строки 100 (что тоже не по PEP8) получается что чуть ли ни каждую строчку еще и разбивать надо на несколько. И уже некуда писать комментарии совсем.

По поводу чтения строчки - в todo добавлю. Подумаю потом на эту тему.

**Comment by Fahreeve** [comment]
ну я на elementary os все починил. На остальных файлменеджерах ничего не сломал?

**Comment by slytomcat** [comment]
Спасибо за помощь - я разобрался в чем было зацикливание, но ваш fix for loop in elementary os - слишком костыльный.... Я тут другой вариант реализовал...  хотя там тоже пришлось велосипед изобретать, что бы отловить повторный вызов обработчика при смене статуса чекбокса назад (при неудаче инициализации файловых расширений). Но так хоть в одном месте правки и более понятен смысл их.

**Comment by slytomcat** [comment]
все решили.

**Comment by Fahreeve** [comment]
гм, почему-то не работает

**Comment by slytomcat** [comment]
Что именно не работает?

**Comment by slytomcat** [comment]
По поводу X-GNOME-Autostart-enabled=true|false

В XFCE используется другой атрибут: Hiden=true|false с обратной логикой (т.е. автозапуска нет если Hidden=true)

По сему встает большущий вопрос - как этот зоопарк обрабатывать?

Я могу проверить и X-GNOME-Autostart-enabled и Hidden, но что мне делать если по судя по одному автозапуск есть, а судя по другому - нет. Как узнать какое окружение - я пока не знаю....

**Comment by Fahreeve** [comment]
а если не париться и писать обе переменные?

**Comment by slytomcat** [comment]
... ну допустим одна говорит, что автостарт разрешен, а вторая - запрещен. 
Не зная какая платформа - можно подбросить монетку и только так решить - сработает автостарт или нет.

**Comment by Fahreeve** [comment]
ну тогда делаем 3 переменные: автостарт из настройки программы и 2 которые для гнома и для xfce и если одна из двух эти отличается от референса, то меняем настройку програмы

**Comment by slytomcat** [comment]
Это гадание на кофейной гуще. Без знания о десктопокружении принимать хоть какое-то решение в такой ситуации это пальцем в небо тыкать.

**Comment by slytomcat** [comment]
Скажите что у вас выдает:
echo $XDG_CURRENT_DESKTOP
echo $DESKTOP_SESSION

**Comment by Fahreeve** [comment]
$ echo $XDG_CURRENT_DESKTOP
Pantheon
$ echo $DESKTOP_SESSION
pantheon

**Comment by Fahreeve** [comment]
а может быть при установке стоит анализировать конфиги других программ, там и видно будет, какую из переменных надо юзать

**Comment by slytomcat** [comment]
Так программ то много как и что искать - это нужно чуть-ли не искуственный интеллект подключать. Индикатор явно требует только демона, а он CLI.
