### ISSUE TITLE
The last version update bug.

### ISSUE THREAD

**Issue by greeklug** [slytomcat/yandex-disk-indicator#5]
After the last update not start well,  
We try it start from terminal and the answer is :
(yandexDiskIndicator.py:9010): Gtk-WARNING **: Theme parsing error: gtk.css:10:0: expected '{' after selectors.
Not serious bug, please check the  /opt/yd-tools/yandexDiskIndicator.py
We try it on Linux Mint 17.2 Cinnamon , Yandex-disk-indicator  version 1.3.1_Py2.

**Comment by slytomcat** [comment]
Seems very strange - yandexDiskIndicator.py has less than 1000 rows but error is on row 9010 "(yandexDiskIndicator.py:9010): ...". In additional I have no idea about "gtk.css" - I don't use any css in the project.....
Is there any more information about the bug?

BTW I'm preparing v.1.4.0 now (most changes in project files locations) but I also changed some code.
May you also try last version from master branch? 
Be aware - in 1.4.0 program catalog moved to /usr/share/yd-tools and main code moved to /usr/bin/yandex-disk-indicator (in previous versions it was just bash wrapper).

**Comment by greeklug** [comment]
Ok, we check it again and inform you.

**Comment by greeklug** [comment]
Ok, now we check it and indicator start well.
And the  "Gtk-WARNING **: Theme parsing error: gtk.css:10:0: expected '{' after selectors." 
is some info from the Cinnamon, nothing important .

**Comment by slytomcat** [comment]
Ok. Good news. 
I'll issue the 1.4.0 realize.

**Comment by slytomcat** [comment]
Fixed in 1.4.0
