### ISSUE TITLE
New version 1.4.0

### ISSUE THREAD

**Issue by greeklug** [slytomcat/yandex-disk-indicator#7]
Before 5 minute download new version 1.4.0  ok.
But Icons lost.
I go to /usr/share/yd-tools/ and see wrong path for icons:

./fm-actions/Nautilus_Nemo/unpublish:zenity --info --window-icon=/opt/yd-tools/icons/yd-128_g.png --ok-label="Закрыть" --title="Yandex.Disk" --text="$*
./fm-actions/Nautilus_Nemo/publish:zenity --info --window-icon /opt/yd-tools/icons/yd-128_g.png --title="Yandex.Disk" --ok-label="Закрыть" --text="Ссылка на файл $*
./fm-actions/Dolphin/unpublish.desktop:X-KDE-Icon=/opt/yd-tools/icons/yd-128_g.png
./fm-actions/Dolphin/unpublish.desktop:Icon=/opt/yd-tools/icons/yd-128_g.png
./fm-actions/Dolphin/unpublish.desktop:Exec=zenity --info --window-icon=/opt/yd-tools/icons/yd-128_g.png --ok-label="Закрыть" --title="Yandex.Disk" --text="Убрать из публикации через Yandex.disk: `yandex-disk unpublish %F`"
./fm-actions/Dolphin/publish.desktop:X-KDE-Icon=/opt/yd-tools/icons/yd-128.png
./fm-actions/Dolphin/publish.desktop:Icon=/opt/yd-tools/icons/yd-128.png
./fm-actions/Dolphin/publish.desktop:Exec=yandex-disk publish %F | xclip -filter -selection clipboard; zenity --info --window-icon=/opt/yd-tools/icons/yd-128.png

**Comment by greeklug** [comment]
New path for icons need to be change to  /usr/share/yd-tools/icons/

**Comment by slytomcat** [comment]
Thanks for your input.

FIXED in 1.4.1
