### ISSUE TITLE
Bug in 1.8.0 on ppa

### ISSUE THREAD

**Issue by linuxmangr** [slytomcat/yandex-disk-indicator#89]
Привет, 
На ppa в версии  1.8.0 есть ошибка.
Я сравнил файл  yandex-disk-indicator.py  здесь и в пакете ppa и есть большие различия.
Нужно их исправить.

**Comment by slytomcat** [comment]
Я там оформил пуллреквест с версии 181 - просто примите их и там уже
правьте.

180 - вообще случайно вышла слишком глючная - попался на том, что давно уже
новую версию гонял и вариант апгрейда с предыдущей не проверил :( два
косяка нашли друг на друга и индикатор крашился до тех пор пока руками в
настройки не внесешь правки.

Так что 180 - забудьте как страшный сон, ставьте 181 (уже залито на ppa)

**Comment by slytomcat** [comment]
Don't install v.1.8.0 - it has critical bug!

Install fixed v.1.8.1 instead (already uploaded to ppa)
