### ISSUE TITLE
I think we need.

### ISSUE THREAD

**Issue by linuxmangr** [slytomcat/yandex-disk-indicator#97]
Hello,
I think we need add translation to  https://github.com/slytomcat/yandex-disk-indicator/blob/master/ya-setup.
Is possible add translation to  ya-setup file ?

**Comment by slytomcat** [comment]
Hi,
Only one thing I'm worry about - I don't know how to translate bash
programs... unfortunately.

Creating a new file with translated texts - dosn't seem a good idea....

But if you or somebody from your team has experience in bash script
localization - i see no problems to translate it.
I would translated it to English too.

2016-01-22 21:36 GMT+03:00 Sergios (aka linuxman) notifications@github.com
:

**Comment by Zirrald** [comment]
Here is an example bash script localization:
https://github.com/CarlDuff/aif
maybe it help.

**Comment by slytomcat** [comment]
Thanks a lot for good example.
I'll tray to implement such solution in ya-setup script.

**Comment by Zirrald** [comment]
small example ;)
![screen2](https://cloud.githubusercontent.com/assets/10292519/13494106/3e1bdbb8-e153-11e5-8352-8de0df3a191b.png)

**Comment by slytomcat** [comment]
Zirrad, Thanks for your contribution. I've slightly changed the language selection and deployed the solution in the package (see last commits in dev branch).

linuxmangr, can you prepare the Greek translation file for ya-setup (see examples in translations/ya-setup-[en|ru].lang files).

**Comment by Zirrald** [comment]
You're welcome!  Keep up the good work :+1:

**Comment by slytomcat** [comment]
Multi-language support added in ya-setup in v.1.8.8. 
Russian, Bulgarian, English translations fully up to date in v.1.8.9
Awaiting for Greek translation update.

**Comment by linuxmangr** [comment]
Hello,
Yes I can add translation, give some days.
